### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by AifeiI** [objectbox/objectbox-java#1007]
AndroidObjectBrowser not working in Android 12

objectBox version: `2.9.1`

app/build.gradle ->
```groovy
android {
    compileSdkVersion 31
    buildToolsVersion "31.0.0"

    defaultConfig {
        applicationId "com.demo"
        minSdkVersion 23
        targetSdkVersion 31
        ... ...
    }

    ... ...
}

```

```java
Caused by: java.lang.IllegalArgumentException: com.demo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at io.objectbox.android.AndroidObjectBrowser.start(AndroidObjectBrowser.java:98)
        at com.demo.DemoApplication.initDB(DemoApplication.kt:116)
        at com.demo.DemoApplication.onCreate(DemoApplication.kt:64)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6708)
        	... 9 more
```

**Comment by greenrobot-team** [comment]
Thanks for reporting, we'll look into this!

For now the only workaround is to keep targeting Android 11 (SDK 30) for debug builds if you want to use the data browser.
