### ISSUE TITLE
Loading native library failed, please report this to us: vendor=The Android Project,os=linux,os.arch=i686,model=null,android=true,linux=true,machine=i686

### ISSUE THREAD

**Issue by sunnyagarwal008** [objectbox/objectbox-java#1030]
Objectbox version: '2.9.1'

Device
Brand:LGE
Model:Nexus 5X
Orientation: Portrait
RAM free: 1.34 GB
Disk free: 484.36 MB
Operating system
Version:Android 8.1.0
Orientation: Portrait
Rooted:No
Crash
Date:27 Nov 2021, 09:00:09
App version:2.0.5 (142)

Here is the crashlytics stack trace:

```
Fatal Exception: java.lang.LinkageError: [ObjectBox] Loading native library failed, please report this to us: vendor=The Android Project,os=linux,os.arch=i686,model=null,android=true,linux=true,machine=i686
       at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:112)
       at io.objectbox.BoxStore.<init>(BoxStore.java:257)
       at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:498)
       at com.risor.core.dagger.BoxStoreModule.provideBoxStore(BoxStoreModule.java:21)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.provideBoxStore(BoxStoreModule_ProvideBoxStoreFactory.java:38)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.get(BoxStoreModule_ProvideBoxStoreFactory.java:29)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.get(BoxStoreModule_ProvideBoxStoreFactory.java:11)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.get$bridge(BoxStoreModule_ProvideBoxStoreFactory.java:25)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.risor.core.repository.OutOfOrderIncomingMessageRepository_Factory.get(OutOfOrderIncomingMessageRepository_Factory.java:23)
       at com.risor.core.repository.OutOfOrderIncomingMessageRepository_Factory.get(OutOfOrderIncomingMessageRepository_Factory.java:9)
       at com.risor.core.helper.MyAccountHelper_Factory.get$bridge(MyAccountHelper_Factory.java:7)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler.initializeBuffer(IncomingUserMessageUpdateHandler.java:404)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler.<init>(IncomingUserMessageUpdateHandler.java:62)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler_Factory.newInstance(IncomingUserMessageUpdateHandler_Factory.java:90)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler_Factory.get(IncomingUserMessageUpdateHandler_Factory.java:66)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler_Factory.get(IncomingUserMessageUpdateHandler_Factory.java:19)
       at com.risor.core.sync.incomingupdatehandler.IncomingActivityUpdateHandler_Factory.get$bridge(IncomingActivityUpdateHandler_Factory.java:4)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.risor.core.sync.IncomingUpdateSyncRunnable.doRun(IncomingUpdateSyncRunnable.java:97)
       at com.risor.core.worker.RisorRunnable.run(RisorRunnable.java:15)
       at com.risor.subscription.UpdateSyncEventSubscriber$onIncomingUpdateSyncEvent$1.invokeSuspend(UpdateSyncEventSubscriber.java:81)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.risor-1waS48-WnVGLue1oE9udzw==/base.apk"],nativeLibraryDirectories=[/data/app/com.risor-1waS48-WnVGLue1oE9udzw==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libobjectbox-jni.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:86)
       at io.objectbox.BoxStore.<init>(BoxStore.java:257)
       at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:498)
       at com.risor.core.dagger.BoxStoreModule.provideBoxStore(BoxStoreModule.java:21)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.provideBoxStore(BoxStoreModule_ProvideBoxStoreFactory.java:38)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.get(BoxStoreModule_ProvideBoxStoreFactory.java:29)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.get(BoxStoreModule_ProvideBoxStoreFactory.java:11)
       at com.risor.core.dagger.BoxStoreModule_ProvideBoxStoreFactory.get$bridge(BoxStoreModule_ProvideBoxStoreFactory.java:25)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.risor.core.repository.OutOfOrderIncomingMessageRepository_Factory.get(OutOfOrderIncomingMessageRepository_Factory.java:23)
       at com.risor.core.repository.OutOfOrderIncomingMessageRepository_Factory.get(OutOfOrderIncomingMessageRepository_Factory.java:9)
       at com.risor.core.helper.MyAccountHelper_Factory.get$bridge(MyAccountHelper_Factory.java:7)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler.initializeBuffer(IncomingUserMessageUpdateHandler.java:404)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler.<init>(IncomingUserMessageUpdateHandler.java:62)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler_Factory.newInstance(IncomingUserMessageUpdateHandler_Factory.java:90)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler_Factory.get(IncomingUserMessageUpdateHandler_Factory.java:66)
       at com.risor.core.sync.incomingupdatehandler.IncomingUserMessageUpdateHandler_Factory.get(IncomingUserMessageUpdateHandler_Factory.java:19)
       at com.risor.core.sync.incomingupdatehandler.IncomingActivityUpdateHandler_Factory.get$bridge(IncomingActivityUpdateHandler_Factory.java:4)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.risor.core.sync.IncomingUpdateSyncRunnable.doRun(IncomingUpdateSyncRunnable.java:97)
       at com.risor.core.worker.RisorRunnable.run(RisorRunnable.java:15)
       at com.risor.subscription.UpdateSyncEventSubscriber$onIncomingUpdateSyncEvent$1.invokeSuspend(UpdateSyncEventSubscriber.java:81)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
```

**Comment by greenrobot-team** [comment]
Thanks for reporting. Is it possible that this is a test device used by the Play Store (e.g. does your app have pre-launch reports enabled)? Actual devices should not use the `i686` architecture.
