### ISSUE TITLE
Invalid argument(s): Missing library

### ISSUE THREAD

**Issue by deliqs** [objectbox/objectbox-java#1036]
**Describe the bug**
The build script gets stuck. When I run "flutter pub run build_runner build" (also with: "--delete-conflicting-outputs") it throws the following error and ends up with 16 uncompleted tasks.

```
Invalid argument(s): Missing library: package:deliqs/models/enums/app_routes.dart
```

After this it just keeps counting the time and every 15 seconds shows the following:
```
[WARNING] No actions completed for 15.0s, waiting on:
  - objectbox_generator:resolver on test/app_wrapper_test.dart
  ....
```

The library that is not found is one of my own enums I use to navigate through my flutter app.
I have already did "flutter clean" and "flutter pub upgrade" but it does not resolve my issue.
I think this happened after I upgraded Flutter to 2.8.0 and Dart to 2.15.

**Basic info (please complete the following information):**
 - ObjectBox version:
        objectbox: ^1.3.0
        objectbox_flutter_libs: ^1.3.0
 - Reproducibility: always
 - Device: N/A
 - OS: N/A

**To Reproduce**
I have no idea.

**Expected behavior**
I expected the script to finish and build my new database model.

**Logs, stack traces**
```
Invalid argument(s): Missing library: package:deliqs/models/enums/app_routes.dart
Available libraries: [dart:typed_data, dart:convert, dart:math, dart:core, dart:_internal, dart:collection, dart:async, dart:isolate, dart:developer, dart:ffi, dart:_js_embedded_names, dart:_js_names, dart:_recipe_syntax, dart:_rti, dart:_foreign_helpe
r, dart:_js_helper, dart:_interceptors, dart:_native_typed_data, dart:web_gl, dart:js_util, dart:_metadata, dart:html_common, dart:indexed_db, dart:svg, dart:web_audio, dart:html, dart:io, dart:_http, dart:js, dart:_js, dart:mirrors, dart:nativewrapper
s, dart:cli, dart:_late_helper, dart:_dart2js_runtime_metrics, dart:_js_primitives, dart:_async_await_error_codes, dart:_js_annotations, dart:_spirv, dart:ui]
#0      LinkedElementFactory.createLibraryElementForReading (package:analyzer/src/summary2/linked_element_factory.dart:74:7)
#1      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:128:14)
#2      LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:177:12)
#3      ElementBuilder._selectLibrary (package:analyzer/src/summary2/element_builder.dart:1018:37)
#4      ElementBuilder.visitImportDirective (package:analyzer/src/summary2/element_builder.dart:598:31)
#5      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5953:50)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7758:20)
#7      ElementBuilder.buildLibraryElementChildren (package:analyzer/src/summary2/element_builder.dart:60:21)
#8      LibraryBuilder.buildElements (package:analyzer/src/summary2/library_builder.dart:109:24)
#9      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:109:15)
#10     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:88:5)
#11     Linker.link (package:analyzer/src/summary2/link.dart:74:5)
#12     link (package:analyzer/src/summary2/link.dart:33:10)
#13     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:176:30)
#14     SetMixin.forEach (dart:collection/set.dart:142:30)
#15     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:113:32)
#16     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:206:7)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#18     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:204:12)
#19     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1574:22)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#21     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1572:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1126:35)
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:24)
<asynchronous suspension>
```

**Code**
This is the file that is breaking the script:

```
enum AppRoutes {
  Home,
  Login,
  EmailLogin,
  Onboarding,
  PreOnboarding,
  SetProtocolFlow,
}
```

**Additional context**
Since the missing file has nothing to do with either my database or the Flutter/Dart framework, I do not know how to give instructions to reproduce this issue. Also this file is not imported in any of my entities.

**Comment by deliqs** [comment]
Removing this file will result in other files popping up in the place of app_routes.dart.

**Comment by deliqs** [comment]
After further investigation, it seemed to be caused by something in a test that I wrote. I think that broke something, which caused the script to break further down the line. I will investigate what exactly was this and will give an update!

**Comment by deliqs** [comment]
Well I can't explain the behavior. So I'm closing this ticket.
