### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: Native method not found: io.objectbox.BoxStore.nativeCreateWithFlatOptions:([B[B)J

### ISSUE THREAD

**Issue by qq728121881** [objectbox/objectbox-java#1054]
java.lang.UnsatisfiedLinkError: Native method not found: io.objectbox.BoxStore.nativeCreateWithFlatOptions:([B[B)J
        at io.objectbox.BoxStore.nativeCreateWithFlatOptions(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:17)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:5)
        at com.zjmy.eink.api.db.ObjectBoxStore.init(ObjectBoxStore.java:6)
        at com.zjmy.eink.home.presenter.activity.HomeActivity.inCreat(HomeActivity.java:6)
        at com.zjmy.mvp.presenter.ActivityPresenter.onCreate(ActivityPresenter.java:12)
        at android.app.Activity.performCreate(Activity.java:5238)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by greenrobot-team** [comment]
Thanks for reporting! This looks like your project has different versions of the Java library (objectbox-java) and native libraries (e.g. objectbox-android or objectbox-linux) added to dependencies. Make sure they all use the same version, then clean and rebuild your project. Let me know if that works!
