### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "**path**/lib/arm64/libobjectbox-jni.so" has bad ELF magic

### ISSUE THREAD

**Issue by StealFeam** [objectbox/objectbox-java#1055]
This crash was recorded on the statistics platform.

**Basic info:**
 - ObjectBox version: 3.0.1
 - Gradle version: 6.1.1 with AGP 3.5.4
 - Reproducibility: occurred once only, that user doesn't seem to have opened the app again.
 - Device: Huawei Mate 9
 - OS: Android 9

**Code**
```
MyObjectBox.builder()
    .name(DB_NAME.substring(0, DB_NAME.indexOf(".")))
    .androidContext(context.getApplicationContext())
    .build();
```

**Logs, stack traces**
```
Caused by: java.lang.LinkageError: [ObjectBox] Loading native library failed, please report this to us: vendor=The Android Project,os=linux,os.arch=aarch64,model=null,android=true,linux=true,machine=aarch64
at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:115)
at io.objectbox.internal.NativeLibraryLoader.checkUnpackLib(NativeLibraryLoader.java:0)
                         ensureLoaded(NativeLibraryLoader.java:0)
at io.objectbox.BoxStore.<init>(BoxStore.java:257)
at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:516)
at com.path.DaoManager.<init>(DaoManager.java:91)
at com.path.DaoManager.getInstance(DaoManager.java:109)
at com.path.StockManager$5.doInBackground(StockManager.java:389)
at com.path.StockManager$5.doInBackground(StockManager.java:386)
at android.os.AsyncTask$2.call(AsyncTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/path/lib/arm64/libobjectbox-jni.so" has bad ELF magic
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1672)
at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:89)
at io.objectbox.internal.NativeLibraryLoader.checkUnpackLib(NativeLibraryLoader.java:0) ensureLoaded(NativeLibraryLoader.java:0)
at io.objectbox.BoxStore.<init>(BoxStore.java:257)
at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:516)
at com.path.DaoManager.<init>(DaoManager.java:91)
at com.path.DaoManager.getInstance(DaoManager.java:109)
at com.path.StockManager$5.doInBackground(StockManager.java:389)
at com.path.StockManager$5.doInBackground(StockManager.java:386)
at android.os.AsyncTask$2.call(AsyncTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:784)

```

**Additional context**
- `app` -- `build.gradle` --  `objectbox-plugin` ---> version 3.0.1

    - impl --- [libA] ---- `objectbox-plugin` ----> version 3.0.1
     
     - impl ---[aar StockManager] ---- `compile with objectbox version 3.1.0`

**Comment by greenrobot-team** [comment]
Thanks for reporting. After researching a bit, it's possible that the shared library file (`libobjectbox-jni.so`) got corrupted somehow. If this only occurred on this device, likely while installing on that device. If it occurs on all devices with that architecture (64-bit ARM) the App Bundle or APK you built is corrupted.

In any case, I would recommend to update to the latest versions of ObjectBox and also the Android Gradle plugin! There have been many bug fixes.

**Comment by StealFeam** [comment]
Only that one user had this situation.
The current fix is to unify the version of ObjectBox and verify it when it goes live.
Thanks for the reply.

**Comment by greenrobot-team** [comment]
@StealFeam OK, so I'm closing this for now. Let us know if this affects more users or devices!
