### ISSUE TITLE
(declaration of 'utils.UtilityHelperKt' appears in /data/app/com.station-2/base.apk:classes2.dex)

### ISSUE THREAD

**Issue by LiuYanshan63** [objectbox/objectbox-java#1082]
Upgrading kotlin and objectbox will crash

kotlin_version = '1.7.0'
objectboxVersion = '3.1.3'

The following version will not crash
kotlin_version = '1.4.32'
objectboxVersion = '3.0.1'

log is：
java.lang.VerifyError: Verifier rejected class utils.UtilityHelperKt due to bad method long utils.UtilityHelperKt.getOverrideStationID(long, java.lang.String)
(declaration of 'utils.UtilityHelperKt' appears in /data/app/com.station-2/base.apk:classes2.dex)
	at com.utils.CashierUtilsKt.payIntentSettle(CashierUtils.kt:98)
	at com.activity.OrderEntryActivity$goToPay$1$1.invoke$lambda-0(OrderEntryActivity.kt:1638)
	at com.activity.OrderEntryActivity$goToPay$1$1.$r8$lambda$apbMGQDHU2PgFgu45XLXr4f2bOs(OrderEntryActivity.kt)
	at com.activity.OrderEntryActivity$goToPay$1$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

code is：

   val dineInTableGroupQb = DBManager.boxFor<axDineInTableGroup>().query {
        equal(axDineInTableGroup_.axDineInTableGroupID, axDineInTableGroupID)
        equal(axDineInTableGroup_.RecDeleted, false)
    }
    when (printRouting) {
        "OverridePackingTicketPrintRouting" -> {
            longId = dineInTableGroupQb.property(axDineInTableGroup_.OverridePackingTicketPrintRouting).findLong()
        }
        else -> {
        }
    }

**Comment by greenrobot-team** [comment]
@LiuYanshan63 The error log says that the issue is with your `utils.UtilityHelperKt.getOverrideStationID` function:
```
java.lang.VerifyError: Verifier rejected class utils.UtilityHelperKt due to bad method long utils.UtilityHelperKt.getOverrideStationID(long, java.lang.String)
```

Let us know if this is still somehow relevant to ObjectBox.

**Comment by LiuYanshan63** [comment]
@greenrobot-team  thx    no bug
