### ISSUE TITLE
LinkageError when two programs use ObjectBox and share the same .dll.

### ISSUE THREAD

**Issue by Ckblck** [objectbox/objectbox-java#1096]
**Describe the bug**
A Java program will not work if another Java program uses ObjectBox.

**Basic info:**
 - ObjectBox version: 3.2.1
 - Reproducibility: always
 - Device: Desktop Java
 - OS: Windows 10 & Windows 11 too

**To Reproduce**
See the `Is there anything special about your app?`.

Probable way to reproduce the behaviour without using Spigot plugins:
1. Create two projects that use ObjectBox and place them in the same folder.
2. Execute each application
3. See error

Way to reproduce the behaviour USING Spigot plugins:
1. Create two Spigot plugins that use ObjectBox.
2. Place the plugins under the `\plugins` folder.
3. Start the server & see the error for one plugin.

**Expected behavior**
ObjectBox should be able to use different `.dll` files in order for this error not to happen. This could be worked around by providing a method to specify the location of the `.dll` file, https://github.com/objectbox/objectbox-java/issues/973

**Logs, stack traces**
```
[21:23:30 WARN]: java.io.FileNotFoundException: objectbox-jni-windows-x64.dll (El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso)
[21:23:30 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[21:23:30 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[21:23:30 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[21:23:30 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//io.objectbox.internal.NativeLibraryLoader.checkUnpackLib(NativeLibraryLoader.java:227)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:75)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//io.objectbox.BoxStore.<init>(BoxStore.java:262)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:516)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//dev.ckblck.referrals.logic.reward.storage.pending.PendingRewardDatabase.loadDatabase(PendingRewardDatabase.java:79)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//dev.ckblck.referrals.logic.reward.storage.pending.PendingRewardDatabase.<init>(PendingRewardDatabase.java:30)
[21:23:30 WARN]:        at Plugin-1.0-SNAPSHOT.jar//dev.ckblck.referrals.Plugin.lambda$onEnable$0(Plugin.java:82)
[21:23:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:23:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:23:30 WARN]: java.util.concurrent.CompletionException: java.lang.LinkageError: [ObjectBox] Loading native library failed, please report this to us: vendor=Amazon.com Inc.,os=windows 10,os.arch=amd64,model=64,linux=false,machine=null
[21:23:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[21:23:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[21:23:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
[21:23:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:23:30 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:23:30 WARN]: Caused by: java.lang.LinkageError: [ObjectBox] Loading native library failed, please report this to us: vendor=Amazon.com Inc.,os=windows 10,os.arch=amd64,model=64,linux=false,machine=null
```

**Additional context**
 - Is there anything special about your app?
 I'm using ObjectBox for Spigot Java plugins. In this context, the `objectbox-jni-windows-x64` is being shared for all the plugins that use ObjectBox, and as far as I'm aware, there is no viable way to modify the location of the `objectbox-jni-windows-x64` file for each instance. Possibly related with https://github.com/objectbox/objectbox-java/issues/973
 The Spigot standalone loads each plugin and when two plugins are using ObjectBox, the error occurrs.

**Comment by greenrobot-team** [comment]
Thanks for reporting! First of all, this is the error message:
`java.io.FileNotFoundException: objectbox-jni-windows-x64.dll (El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso)`
Translation: `The process does not have access to the file because it is in use by another process`

It appears this is happening while trying to extract the native library and trying to write to an existing library file.
https://github.com/objectbox/objectbox-java/blob/7d5f6ca323cbb357f97a4bb9721e6326ef95fb3e/objectbox-java/src/main/java/io/objectbox/internal/NativeLibraryLoader.java#L224-L227

There is a check if the file already exists to prevent extracting again. However, there might be a race if two processes extract in parallel.

We might be able to solve this by introducing file locking (assuming that loading the library can happen from multiple processes in parallel).

We'll update this issue when we know a fix is available.

As for workarounds: can you change the working directory of the plugins so they extract the native library to a different folder? Or prevent them running in parallel?

**Comment by Ckblck** [comment]
> can you change the working directory of the plugins so they extract the native library to a different folder? Or prevent them running in parallel?

Unfortunately, I'm afraid I'm unable to work around this issue, I've checked if I could take advantage of reflection, but without success.

Nevertheless, I'm thankful the issue has been registered, I'll patiently wait for the fix.
