### ISSUE TITLE
Support Gradle build cache

### ISSUE THREAD

**Issue by rAseri** [objectbox/objectbox-java#1114]
The bug is occurred in an Android Project.

**Description of the bug**
During a [manual conflict resolution](https://docs.objectbox.io/advanced/meta-model-ids-and-uids#manual-conflict-resolution), the `objectbox-models/default.json` file may accidentally contain duplicated `indexId` entries. During the build time, we don't have any errors. The project builds successfully, and the build output is cached to the Gradle Build Cache. Only at runtime, when we build `BoxStore` instance, an error occurred: `io.objectbox.exception.DbSchemaException: Duplicate index ID 2 found for property ...`. Moreover, when a developer fixes duplicated `indexId` entries in the `objectbox-models/default.json` file and rebuilds the project, the error is still in place due to the result of the previous build is used from the Gradle Build Cache. It incurs hard-to-debug problems for our dev team. 

**Basic info:**
 - ObjectBox version: 3.5.1
 - Reproducibility: always
 - Device: any device
 - OS: reproduced on Android 11, 13

**Steps to reproduce the behavior:**

1. Activate the Gradle Build Cache: add `org.gradle.caching=true` in the `gradle.properties` file.
2. Add two ObjectBox entities (e.g. `User` and `Company`) with the unique `name` property.
3. Build the project to generate a `objectbox-models/default.json` file.
4. Make changes to the `objectbox-models/default.json` file: set the same value to both `indexId` entries (`Company.name` and `User.name`).
5. Rebuild the project. 
6. Install APK and launch the app. There is the error: `io.objectbox.exception.DbSchemaException: Duplicate index ID 2 found for property ...`
7. Fix duplicated `indexId` in the `objectbox-models/default.json` file.
8. Rebuild the project.
9. Install APK and launch the app. There is still the same error. The result of the previous build is used.

**Expected behavior**
- The `Duplicate index ID` error should occur during the build time, not at runtime.  
- Any change to the `objectbox-models/default.json` file should lead to the invalidation of the Gradle Build Cache to prevent the usage of stale data from the previous build.

**Code**
I've prepared the demo project to reproduce the problem with the described above steps:
https://github.com/rAseri/ObjectBoxDemo

**Logs, stack traces**
```
Process: com.example.myapplication, PID: 24377
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: io.objectbox.exception.DbSchemaException: Duplicate index ID 2 found for property User.name
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by greenrobot-team** [comment]
Thanks for reporting! I guess the culprit is that the model file is only touched by the annotation processor. We need to check if it can somehow be indicated to Gradle that the processor has the model file as an input and output.

(Somewhat related, though configuration cache other than build cache is still experimental: https://github.com/objectbox/objectbox-java/issues/948)

**Comment by rAseri** [comment]
Thanks for your reply!

I am not a Gradle expert, but it looks like a working solution (I'm using Kotlin Scripts here):
```kotlin
    plugins {
        id("io.objectbox")
        // ...
    }
  
    // ...
    tasks.withType<org.jetbrains.kotlin.gradle.tasks.BaseKapt>().configureEach {
        inputs.file("objectbox-models/default.json")
    }
```

I added the model file as an input for `BaseKapt` task. Now every change in the model file causes the `kaptDebugKotlin` task to rerun as expected!
![Screenshot 2023-02-13 at 17 55 39](https://user-images.githubusercontent.com/3706717/218491950-4ff75698-af32-4dbf-baa4-ffaac6d07a4c.jpg)

**Comment by rAseri** [comment]
> Maybe we can also do this automatically with the Gradle plugin.

I think it's a good idea!

**Comment by greenrobot-team** [comment]
@rAseri Thanks for testing this! Looks like adding an input to the kapt (or Java equivalent annotation processor) task is what we will let the Gradle plugin do then.

For our reference, this is internal issue `objectbox-java#174`

**Comment by greenrobot-team** [comment]
While researching something related, I noticed that kapt also has an [option to turn off build cache](https://kotlinlang.org/docs/kapt.html#gradle-build-cache-support) for itself exactly for this reason.

So as an alternative to configuring the model JSON file as an input [like suggested above](https://github.com/objectbox/objectbox-java/issues/1114#issuecomment-1428090667) (and if done correctly also as output, which may lead to further issues), it should also be possible to use this workaround:

```kotlin
kapt {
    useBuildCache = false
}
```
