### ISSUE TITLE
 Failed to lookup symbol 'obx_version_is_at_least'

### ISSUE THREAD

**Issue by FlippedOvO** [objectbox/objectbox-java#1145]
objectbrowser got error

 - ObjectBox version 2.2.0
 - Reproducibility: always
 - Device: Xiaomi 12S
 - OS:Android 13

1. openStore
2. got error  Failed to lookup symbol 'obx_version_is_at_least'

```dart
await openStore(directory: path)
``` 

```
E/flutter (25783): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'obx_version_is_at_least': undefined symbol: obx_version_is_at_least
E/flutter (25783): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
E/flutter (25783): #1      ObjectBoxC._version_is_at_leastPtr (package:objectbox/src/native/bindings/objectbox_c.dart:60:80)
E/flutter (25783): #2      ObjectBoxC._version_is_at_leastPtr (package:objectbox/src/native/bindings/objectbox_c.dart)
E/flutter (25783): #3      ObjectBoxC._version_is_at_least (package:objectbox/src/native/bindings/objectbox_c.dart:63:7)
E/flutter (25783): #4      ObjectBoxC._version_is_at_least (package:objectbox/src/native/bindings/objectbox_c.dart)
E/flutter (25783): #5      ObjectBoxC.version_is_at_least (package:objectbox/src/native/bindings/objectbox_c.dart:52:12)
E/flutter (25783): #6      _isSupportedVersion (package:objectbox/src/native/bindings/bindings.dart:95:51)
E/flutter (25783): #7      loadObjectBoxLib (package:objectbox/src/native/bindings/bindings.dart:108:8)
E/flutter (25783): #8      C (package:objectbox/src/native/bindings/bindings.dart:119:22)
E/flutter (25783): #9      C (package:objectbox/src/native/bindings/bindings.dart)
E/flutter (25783): #10     new Model (package:objectbox/src/native/model.dart:19:31)
E/flutter (25783): #11     new Store (package:objectbox/src/native/store.dart:192:21)
E/flutter (25783): #12     openStore (package:im_app/objectbox.g.dart:472:5)
E/flutter (25783): #13     DB.init (package:im_app/utils/db/db.dart:27:27)
E/flutter (25783): <asynchronous suspension>
E/flutter (25783): #14     CurrentUserExtension.initCurrentUser (package:im_app/observer/controller/global.dart:57:5)
E/flutter (25783): <asynchronous suspension>
E/flutter (25783): #15     AccountLoginController.login (package:im_app/modules/login/account_login/account_login_controller.dart:23:5)
E/flutter (25783): <asynchronous suspension>
E/flutter (25783): 

```

my build.gradle

```
configurations {
    debugImplementation {
        exclude group: 'io.objectbox', module: 'objectbox-android'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    debugImplementation("io.objectbox:objectbox-android-objectbrowser:2.2.0")
}

```

**Comment by FlippedOvO** [comment]
if i use version 2.2.1 i got this error

```
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find io.objectbox:objectbox-android-objectbrowser:2.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://repo.maven.apache.org/maven2/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://storage.googleapis.com/download.flutter.io/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://jitpack.io/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://jcenter.bintray.com/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
     Required by:
         project :app

```

**Comment by greenrobot-team** [comment]
This is an issue with our Dart/Flutter library. As I see you have already created [another issue](https://github.com/objectbox/objectbox-dart/issues/554) there closing this one.
