### ISSUE TITLE
io.objectbox.exception.DbException: Could not get from cursor (-30787) (error code -30787)

### ISSUE THREAD

**Issue by Logphi** [objectbox/objectbox-java#1168]
HI, our app use objectbox to save data，it worked very well before，but today i receive  a user`s bug report

```
io.objectbox.exception.DbException: Could not get from cursor (-30787) (error code -30787)
	at io.objectbox.Cursor.nativeGetEntity(Native Method)
	at io.objectbox.Cursor.get(SourceFile:1)
	at io.objectbox.Box.get(SourceFile:2)
	at io.objectbox.relation.ToOne.getTarget(SourceFile:7)
	at io.objectbox.relation.ToOne.getTarget(SourceFile:1)
	at com.yuwell.cgm.data.source.local.dao.GlucoseSyncDAO.getTransmitterId(SourceFile:5)
	at com.yuwell.cgm.data.source.local.repository.SyncRepository.getTransmitterId(SourceFile:1)
	at com.yuwell.cgm.utils.iot.IotConnectUtil.lambda$getUnregisterIotTransmitter$9(SourceFile:1)
	at com.yuwell.cgm.utils.iot.IotConnectUtil.m(Unknown Source:0)
	at h5.l.subscribe(Unknown Source:2)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(SourceFile:3)
	at io.reactivex.Observable.subscribe(SourceFile:14)
	at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(SourceFile:4)
	at io.reactivex.Observable.subscribe(SourceFile:14)
	at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(SourceFile:4)
	at io.reactivex.Observable.subscribe(SourceFile:14)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$b.run(SourceFile:1)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:3)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

Device Manufacturer: OPPO
Device Model       : PERM10
Android Version    : 11
Android SDK        : 30

objectboxVersion = '3.7.0'

How can I fix the error? thanks

**Comment by greenrobot-team** [comment]
Thanks for reporting! Based on [some past reports](https://github.com/objectbox/objectbox-java/issues?q=is%3Aissue+30787) this device might have run into a low memory issue. As it appears your project is using RxJava, check that e.g. queries or even BoxStore and other resources are properly cleaned up once done with them.

We welcome any additional info about this to help any other affected users!
