### ISSUE TITLE
Caused by: java.lang.IllegalStateException: No DB catalog present

### ISSUE THREAD

**Issue by whatshappen** [objectbox/objectbox-java#1169]
**Code:**
val file = File(SDCardUtils.getSDCardPathByEnvironment() + "/CustomFile/dbFile")
if (!file.exists()) {
file.exists()
}
MyObjectBox.builder()
.androidContext(context.applicationContext)
.directory(file)
.build()
**Error:**
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8401)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalStateException: No DB catalog present
at io.objectbox.BoxStore.nativeCreateWithFlatOptions(Native Method)
at io.objectbox.BoxStore.(BoxStore.java:271)
at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:591)

**Comment by whatshappen** [comment]
机型：xiaomi 手机

**Comment by greenrobot-team** [comment]
Thanks for reporting! To help us diagnose this issue, please answer some questions. How often does this occur? Does this only occur on that device model? What version of ObjectBox is used? What version of Android is used?

See [the comment in #865](https://github.com/objectbox/objectbox-java/issues/865#issuecomment-666635847) for potential solutions. As the file is on an SD card this might be a case of file corruption.

**Comment by whatshappen** [comment]
crash:100%
current only xiaomi device
objectbox.gradle version:3.7.1
io.objectbox:objectbox-kotlin:3.7.1
Android13

**Comment by greenrobot-team** [comment]
@whatshappen Thanks! Does the app use [multiple processes](https://developer.android.com/guide/components/processes-and-threads#Processes) by any chance?

**Comment by Lxingzhi** [comment]
this code only use getSDCardPathByEnvironment()    
no use multiple processes

**Comment by whatshappen** [comment]
> @whatshappen Thanks! Does the app use [multiple processes](https://developer.android.com/guide/components/processes-and-threads#Processes) by any chance?

no，init crash, is main thread

**Comment by 360060316** [comment]
I have also encountered this issue. Please fix it as soon as possible. Xiaomi 9 is normal, Xiaomi 10 is not normal, and Xiaomi 11 is normal

**Comment by 360060316** [comment]
Copy the database file from the phone that does not report an error to the phone that reports an error, and it can be used normally

**Comment by greenrobot-team** [comment]
@360060316 Is it possible that the database file is corrupted due to a file system issue? This would explain the error message.

In this case the only option is to catch the above exception, delete the database files and then try to open a new BoxStore.
