### ISSUE TITLE
ObjectBox returns more elements than what it should when using `equal()` query

### ISSUE THREAD

**Issue by alghe-global** [objectbox/objectbox-java#1176]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues)

### Build info

- ObjectBox version: 3.8.0
- OS: Debian 12
- Device/ABI/architecture: x86-64

### Steps to reproduce

https://github.com/alghe-global/Kotlin/tree/5dca886df81e9f770ed912edce31b77ec7bdae3e/AndroidCodeLabs/ObjectBoxExample

- `Image.kt` contains entities
- `ImageRepository.kt` contains methods that run asynchronously (of interest here is: `getLatest10ImagesInCity()`)
- `ObjectBoxImageRepositoryTest.kt` contains the tests that perform the queries on storeBox

Run tests in `ObjectBoxImageRepositoryTest.kt`, in particular `testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity`.

### Expected behavior

Only one match should take place: the one matching the city and country as `String`.

### Actual behavior

ObjectBox returns the entire list of entities.

### Code

https://github.com/alghe-global/Kotlin/tree/5dca886df81e9f770ed912edce31b77ec7bdae3e/AndroidCodeLabs/ObjectBoxExample

<details><summary>Code</summary>

```kotlin
package com.example.objectboxexample

import io.objectbox.Box
import io.objectbox.BoxStore
import io.objectbox.kotlin.boxFor
import io.objectbox.query.QueryBuilder
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

interface ImageRepository {
    suspend fun getLatest10ImagesInCity(city: String, country: String): Flow<List<Image>>
    
    suspend fun getLatest10ImagesInCountry(country: String): Flow<List<Image>>

    suspend fun getLatest10ImagesByOwner(user: String): Flow<List<Image>>
}

class ObjectBoxImageRepository(
    val boxStore: BoxStore
) : ImageRepository {

    private val imageBox: Box<Image> = boxStore.boxFor()

    override suspend fun getLatest10ImagesInCity(city: String, country: String): Flow<List<Image>> {
        return flow {
            val query = imageBox.query().run {
                Image_.location.equal(
                    "${city},${country}",
                    QueryBuilder.StringOrder.CASE_INSENSITIVE
                )
                orderDesc(Image_.timestamp)
            }
            val imagesInCityList = query.build().find(0, 10)
            emit(imagesInCityList)
        }
    }

    override suspend fun getLatest10ImagesInCountry(country: String): Flow<List<Image>> {
        return flow {
            val query = imageBox.query().run {
                contains(
                    Image_.location,
                    ",$country",
                    QueryBuilder.StringOrder.CASE_INSENSITIVE
                )
                orderDesc(Image_.timestamp)
            }
            val imagesInCountryList = query.build().find(0, 10)
            emit(imagesInCountryList)
        }
    }

    override suspend fun getLatest10ImagesByOwner(owner: String): Flow<List<Image>> {
        return flow {
            val query = imageBox.query().run {
                Image_.owner.equal(owner)
                orderDesc(Image_.timestamp)
            }
            val imagesByUserList = query.build().find(0, 10)
            emit(imagesByUserList)
        }
    }
}
```
```kotlin
package com.example.objectboxexample.mock

import com.example.objectboxexample.Image

class ImageMockDataSource {
    fun generateMockData(): List<Image> {
        val imageOwner = "my@email.tld"

        val imageOne = "city1"
        val locationOne = "country1"
        val timestampOne = 0L

        val imageTwo = "city2"
        val locationTwo = "country2"
        val timestampTwo = 1L

        val imageThree = "city3"
        val locationThree = "country3"
        val timestampThree = 2L

        val imageFour = "city4"
        val locationFour = "country4"
        val timestampFour = 3L

        val imageFive = "city5"
        val locationFive = "country5"
        val timestampFive = 4L

        val imageSix = "city6"
        val locationSix = "country6"
        val timestampSix = 5L

        val imageSeven = "city7"
        val locationSeven = "country7"
        val timestampSeven = 6L

        val imageEight = "city8"
        val locationEight = "country8"
        val timestampEight = 7L

        val imageNine = "city9"
        val locationNine = "country9"
        val timestampNine = 8L

        val imageTen = "city10"
        val locationTen = "country10"
        val timestampTen = 9L

        val imageList = listOf(
            Image(
                location = "${imageOne},${locationOne}",
                timestamp = timestampOne,
                owner = imageOwner
            ),
            Image(
                location = "${imageTwo},${locationTwo}",
                timestamp = timestampTwo,
                owner = imageOwner
            ),
            Image(
                location = "${imageThree},${locationThree}",
                timestamp = timestampThree,
                owner = imageOwner
            ),
            Image(
                location = "${imageFour},${locationFour}",
                timestamp = timestampFour,
                owner = imageOwner
            ),
            Image(
                location = "${imageFive},${locationFive}",
                timestamp = timestampFive,
                owner = imageOwner
            ),
            Image(
                location = "${imageSix},${locationSix}",
                timestamp = timestampSix,
                owner = imageOwner
            ),
            Image(
                location = "${imageSeven},${locationSeven}",
                timestamp = timestampSeven,
                owner = imageOwner
            ),
            Image(
                location = "${imageEight},${locationEight}",
                timestamp = timestampEight,
                owner = imageOwner
            ),
            Image(
                location = "${imageNine},${locationNine}",
                timestamp = timestampNine,
                owner = imageOwner
            ),
            Image(
                location = "${imageTen},${locationTen}",
                timestamp = timestampTen,
                owner = imageOwner
            )
        )
        return imageList
    }
}
```
```kotlin
package com.example.objectboxexample

import app.cash.turbine.test
import com.example.objectboxexample.mock.ImageMockDataSource
import io.objectbox.BoxStore
import io.objectbox.config.DebugFlags
import io.objectbox.kotlin.boxFor
import junit.framework.TestCase.assertEquals
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.io.File

open class ObjectBoxImageRepositoryTest {

    private lateinit var repository: ImageRepository

    private var _store: BoxStore? = null
    protected val boxStore: BoxStore
        get() = _store!!

    @Before
    fun setUp() {
        /** Delete any files in the test directory
         * before each test to start with a clean database
         */
        BoxStore.deleteAllFiles(TEST_DIRECTORY)
        _store = MyObjectBox.builder()
            /** Use a custom directory to store the database files in */
            .directory(TEST_DIRECTORY)
            /** Enable debug flags for more detailed ObjectBox log output */
            .debugFlags(DebugFlags.LOG_QUERIES or DebugFlags.LOG_QUERY_PARAMETERS)
            .build()

        repository = ObjectBoxImageRepository(boxStore)
    }

    @After
    fun tearDown() {
        /**
         * Close the database, reset pointer and
         * delete all files in the test directory
         */
        _store?.close()
        _store = null
        BoxStore.deleteAllFiles(TEST_DIRECTORY)
    }

    @Test
    fun testGetLatest10ImagesInCity_emptyBox_returnsEmptyList() = runTest {
        val city = "city1"
        val country = "country1"
        repository.getLatest10ImagesInCity(city, country).test {
            val emission = awaitItem()
            awaitComplete()
            assertEquals(emptyList<Image>(), emission)
        }
    }

    @Test
    fun testGetLatest10ImagesInCountry_emptyBox_returnsEmptyList() = runTest {
        val country = "country10"
        repository.getLatest10ImagesInCountry(country).test {
            val emission = awaitItem()
            awaitComplete()
            assertEquals(emptyList<Image>(), emission)
        }
    }

    @Test
    fun testGetLatest10ImagesByOwner_emptyBox_returnsEmptyList() = runTest {
        val eventOwner = "my@email.tld"
        repository.getLatest10ImagesByOwner(eventOwner).test {
            val emission = awaitItem()
            awaitComplete()
            assertEquals(emptyList<Image>(), emission)
        }
    }

    @Test
    fun testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity() = runTest {
        val city = "city1"
        val country = "country1"
        val images = ImageMockDataSource().generateMockData()

        /** Insert test Images into the database */
        boxStore.boxFor<Image>().put(images)

        repository.getLatest10ImagesInCity(city, country).test {
            val emission = awaitItem()
            awaitComplete()
            assertEquals(listOf(images[0]), emission)
        }
    }

    @Test
    fun testGetLatest10ImagesInCountry_populatedBox_emitsExpectedImagesForCountry() = runTest {
        val country = "country10"
        val images = ImageMockDataSource().generateMockData()

        /** Insert test Images into the database */
        boxStore.boxFor<Image>().put(images)

        repository.getLatest10ImagesInCountry(country).test {
            val emission = awaitItem()
            awaitComplete()
            assertEquals(listOf(images[9]), emission)
        }
    }

    @Test
    fun testGetLatest10ImagesByOwner_populatedBox_emitsExpectedImagesByOwner() = runTest {
        val owner = "my@email.tld"
        val images = ImageMockDataSource().generateMockData()

        /** Insert test Images into the database */
        boxStore.boxFor<Image>().put(images)

        repository.getLatest10ImagesByOwner(owner).test {
            val emission = awaitItem()
            awaitComplete()
            assertEquals(images.reversed(), emission)
        }
    }

    companion object {
        private val TEST_DIRECTORY = File("mytests/test-db")
    }
}
```

</details>

### Logs, stack traces

<details><summary>Logs</summary>

```console
junit.framework.AssertionFailedError: expected:<[Image(id=1, timestamp=0, location=city1,country1, owner=my@email.tld)]> but was:<[Image(id=10, timestamp=9, location=city10,country10, owner=my@email.tld), Image(id=9, timestamp=8, location=city9,country9, owner=my@email.tld), Image(id=8, timestamp=7, location=city8,country8, owner=my@email.tld), Image(id=7, timestamp=6, location=city7,country7, owner=my@email.tld), Image(id=6, timestamp=5, location=city6,country6, owner=my@email.tld), Image(id=5, timestamp=4, location=city5,country5, owner=my@email.tld), Image(id=4, timestamp=3, location=city4,country4, owner=my@email.tld), Image(id=3, timestamp=2, location=city3,country3, owner=my@email.tld), Image(id=2, timestamp=1, location=city2,country2, owner=my@email.tld), Image(id=1, timestamp=0, location=city1,country1, owner=my@email.tld)]>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at junit.framework.TestCase.assertEquals(TestCase.java:246)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1$1.invokeSuspend(ObjectBoxImageRepositoryTest.kt:93)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:149)
	at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invokeSuspend(flow.kt:91)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invoke(flow.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invokeSuspend(flow.kt:83)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2.invokeSuspend(flow.kt:88)
	at app.cash.turbine.FlowKt$turbineScope$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2.invoke(flow.kt)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invokeSuspend(coroutines.kt:89)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invoke(coroutines.kt)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at app.cash.turbine.CoroutinesKt.reportTurbines(coroutines.kt:88)
	at app.cash.turbine.FlowKt.turbineScope-k1IrOU0(flow.kt:80)
	at app.cash.turbine.FlowKt.turbineScope-k1IrOU0$default(flow.kt:75)
	at app.cash.turbine.FlowKt.test-C2H2yOE(flow.kt:141)
	at app.cash.turbine.FlowKt.test-C2H2yOE$default(flow.kt:136)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invokeSuspend(ObjectBoxImageRepositoryTest.kt:90)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invokeSuspend(flow.kt:83)
	at app.cash.turbine.FlowKt$turbineScope$2.invokeSuspend(flow.kt:88)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invokeSuspend(coroutines.kt:89)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invokeSuspend(ObjectBoxImageRepositoryTest.kt:90)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)
Caused by: junit.framework.AssertionFailedError: expected:<[Image(id=1, timestamp=0, location=city1,country1, owner=my@email.tld)]> but was:<[Image(id=10, timestamp=9, location=city10,country10, owner=my@email.tld), Image(id=9, timestamp=8, location=city9,country9, owner=my@email.tld), Image(id=8, timestamp=7, location=city8,country8, owner=my@email.tld), Image(id=7, timestamp=6, location=city7,country7, owner=my@email.tld), Image(id=6, timestamp=5, location=city6,country6, owner=my@email.tld), Image(id=5, timestamp=4, location=city5,country5, owner=my@email.tld), Image(id=4, timestamp=3, location=city4,country4, owner=my@email.tld), Image(id=3, timestamp=2, location=city3,country3, owner=my@email.tld), Image(id=2, timestamp=1, location=city2,country2, owner=my@email.tld), Image(id=1, timestamp=0, location=city1,country1, owner=my@email.tld)]>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at junit.framework.TestCase.assertEquals(TestCase.java:246)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1$1.invokeSuspend(ObjectBoxImageRepositoryTest.kt:93)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:149)
	at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invokeSuspend(flow.kt:91)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invoke(flow.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invokeSuspend(flow.kt:83)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2.invokeSuspend(flow.kt:88)
	at app.cash.turbine.FlowKt$turbineScope$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$turbineScope$2.invoke(flow.kt)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invokeSuspend(coroutines.kt:89)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invoke(coroutines.kt)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at app.cash.turbine.CoroutinesKt.reportTurbines(coroutines.kt:88)
	at app.cash.turbine.FlowKt.turbineScope-k1IrOU0(flow.kt:80)
	at app.cash.turbine.FlowKt.turbineScope-k1IrOU0$default(flow.kt:75)
	at app.cash.turbine.FlowKt.test-C2H2yOE(flow.kt:141)
	at app.cash.turbine.FlowKt.test-C2H2yOE$default(flow.kt:136)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invokeSuspend(ObjectBoxImageRepositoryTest.kt:90)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest$testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity$1.invoke(ObjectBoxImageRepositoryTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:322)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:310)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:168)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:160)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
	at com.example.objectboxexample.ObjectBoxImageRepositoryTest.testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity(ObjectBoxImageRepositoryTest.kt:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)


com.example.objectboxexample.ObjectBoxImageRepositoryTest > testGetLatest10ImagesInCity_populatedBox_emitsExpectedImagesForCity FAILED
    junit.framework.AssertionFailedError at Assert.java:57
        Caused by: junit.framework.AssertionFailedError at ObjectBoxImageRepositoryTest.kt:82
6 tests completed, 1 failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///home/antar/Development/Kotlin/AndroidCodeLabs/ObjectBoxExample/app/build/reports/tests/testDebugUnitTest/index.html
* Try:
> Run with --scan to get full insights.
BUILD FAILED in 1s
```

</details>

**Comment by alghe-global** [comment]
I've tried using `filter()` however this seems to be unsupported:

```diff
diff --git a/AndroidCodeLabs/ObjectBoxExample/app/src/main/java/com/example/objectboxexample/ImageRepository.kt b/AndroidCodeLabs/ObjectBoxExample/app/src/main/java/com/example/objectboxexample/ImageRepository.kt
index 5c1cd19..f79ed0e 100644
--- a/AndroidCodeLabs/ObjectBoxExample/app/src/main/java/com/example/objectboxexample/ImageRepository.kt
+++ b/AndroidCodeLabs/ObjectBoxExample/app/src/main/java/com/example/objectboxexample/ImageRepository.kt
@@ -24,10 +24,12 @@ class ObjectBoxImageRepository(
     override suspend fun getLatest10ImagesInCity(city: String, country: String): Flow<List<Image>> {
         return flow {
             val query = imageBox.query().run {
+                val cityCountry = "${city},${country}".lowercase()
                 Image_.location.equal(
-                    "${city},${country}",
+                    cityCountry,
                     QueryBuilder.StringOrder.CASE_INSENSITIVE
                 )
+                filter { image -> image.location == cityCountry }
                 orderDesc(Image_.timestamp)
             }
             val imagesInCityList = query.build().find(0, 10)
```

any ideas on how to get the exact match working?

**Comment by greenrobot-team** [comment]
My best guess is that the Kotlin `.run { }` syntax does not work with QueryBuilder. See https://docs.objectbox.io/queries on how to build queries. Let me know if that is the issue.

**Comment by alghe-global** [comment]
Nailed it! `.run { }` is useless. Building a query like in the docs did the trick.

Happy 1001th closed issue, and, thanks again!
