### ISSUE TITLE
@ Relation ID property must be of type long

### ISSUE THREAD

**Issue by obianachebe** [objectbox/objectbox-java#374]
First of all, wanted to say thanks for a great well-supported library. Terrific work!

## Issue Basics
- ObjectBox version: *1.4.1*
- Reproducibility: *always*

### Description
I have two data classes one called `FoodEntryEntity` and another called `FoodEntity`. A `FoodEntryEntity` has a `ToOne` relationship to a FoodEntity. Both classes share a property named `foodId`. When I attempt to build the project I get thrown this: 

`@ Relation ID property must be of type long: Property foodId of FoodEntryEntity`

If I change the property name to `foodEntryFoodId` the project compiles just fine. 

One thing to note: I did originally annotate the `foodId` property in `FoodEntity` with @Id before changing it. I deleted and recreated the default.json files as well. See code below

### Logs & stackstraces
```
Error:[kapt] An exception occurred: java.lang.RuntimeException: @Relation ID property must be of type long: Property foodId of FoodEntryEntity
	at io.objectbox.generator.model.Property.convertToRelationId(Property.java:440)
	at io.objectbox.generator.model.Entity.addToOne(Entity.java:254)
	at io.objectbox.processor.Relations.resolveToOne(Relations.kt:201)
	at io.objectbox.processor.Relations.resolve(Relations.kt:161)
	at io.objectbox.processor.ObjectBoxProcessor.findAndParse(ObjectBoxProcessor.kt:156)
	at io.objectbox.processor.ObjectBoxProcessor.process(ObjectBoxProcessor.kt:123)
	at org.jetbrains.kotlin.kapt3.ProcessorWrapper.process(annotationProcessing.kt:133)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:89)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:46)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:221)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:177)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:90)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:84)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:376)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:67)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:367)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:132)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:162)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:109)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:53)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:387)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:97)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:895)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:97)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:925)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:894)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:386)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Entities
```kotlin
@Entity
data class FoodEntity(
        // Identifiers
        @Id
        var id: Long = 0,

        @Index
        var foodId: String? = null,

        // Properties
        var foodName: String = ""
)
```

```kotlin
@Entity
data class FoodEntryEntity(
        // Identifiers
        @Id
        var id: Long = 0,

        @Index
        var foodEntryId: String? = null,

        // Properties
        var foodId: String? = null,

        // Relationships
        var food: ToOne<FoodEntity>? = null
)
```

**Comment by greenrobot-team** [comment]
Short answer: yes, the easiest fix is to rename the `foodId` property to something else. Alternative below.

In a bit more detail: each `ToOne` is actually saved in the database by storing the ID of the `ToOne` target.

So for each `ToOne` ObjectBox adds an ID property to your entity named like the `ToOne` field appended with `Id`. So for `food: ToOne` the ID property is `foodId: Long`. This is [only hinted at by the documentation](http://objectbox.io/documentation/relations/#Initialization_Magic) (our bad :() and by looking at your `default.json` model file.

You might want to have direct access to that target ID property instead of going through `ToOne.getTargetId()`/`ToOne.setTargetId(Long)`. So you can explicitly define it in your class, like you did. But it must be of type `Long` because it stores an object ID.

You can change the expected name of the target ID property by adding an annotation to the `ToOne`:
```
@TargetIdProperty("foodEntityId")
var food: ToOne<FoodEntity>? = null
```

-ut
