### ISSUE TITLE
java.util.concurrent.TimeoutException: io.objectbox.BoxStore.finalize() timed out after 120 seconds

### ISSUE THREAD

**Issue by Oo121oO** [objectbox/objectbox-java#401]
java.util.concurrent.TimeoutException: io.objectbox.BoxStore.finalize() timed out after 120 seconds
	at io.objectbox.BoxStore.close(BoxStore.java:392)
	at io.objectbox.BoxStore.finalize(BoxStore.java:265)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:214)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:193)
	at java.lang.Thread.run(Thread.java:818)

BRAND：OPPO OPPO R9sk
API LEVEL：Android 6.0.1

Is there a deadlock here?

    private static void verifyNotAlreadyOpen(String canonicalPath) {
        synchronized (openFiles) {
            int tries = 0;
            while (tries < 5 && openFiles.contains(canonicalPath)) {
                tries++;
                System.gc();
                System.runFinalization();
                System.gc();
                System.runFinalization();
                try {
                    openFiles.wait(100);
                } catch (InterruptedException e) {
                    // Ignore
                }
            }
            if (!openFiles.add(canonicalPath)) {
                throw new DbException("Another BoxStore is still open for this directory: " + canonicalPath +
                        ". Hint: for most apps it's recommended to keep a BoxStore for the app's life time.");
            }
        }
    }

**Comment by core2root** [comment]
Same problem here.
When i close my app (onDestroy() of MainActivity) but the Application class is still alive, and them return to the app and try to build MyObjectBox with applicationContext it stuck at verifyNotAlreadyOpen()->isFileOpen() at line 271 ( System.runFinalization() )
is there something to do with it?
Tried on Xiaomi mi 6 OS version: 8.0.0

**Comment by greenrobot-team** [comment]
Answered in #625.

Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
-ut
