### ISSUE TITLE
Detached entities 'ToMany.addAll' throws error

### ISSUE THREAD

**Issue by zoltish** [objectbox/objectbox-java#412]
## Issue Basics
- ObjectBox version 1.4.4
- Reproducibility: Always

## Reproducing the bug
When creating entities (for inserting into ObjectBox), the ToMany field will throw this error if I use .addAll(list) _it works if I use .add(entity) in a loop over the list_.

### Code
`entity.bodyparts.addAll(bodyparts)`

### Logs & stackstraces
`   io.objectbox.exception.DbDetachedException: Cannot resolve relation for detached entities
        at io.objectbox.relation.ToMany.ensureBoxes(ToMany.java:144)
        at io.objectbox.relation.ToMany.ensureEntities(ToMany.java:184)
        at io.objectbox.relation.ToMany.ensureEntitiesWithTrackingLists(ToMany.java:155)
        at io.objectbox.relation.ToMany.trackAdd(ToMany.java:230)
        at io.objectbox.relation.ToMany.addAll(ToMany.java:264)`

## Entities
` lateinit var bodyparts: ToMany<BodypartEntity>`

## Misc
As mentioned above, the issue seems to be with .addAll specifically, whereas .add does work. The issue happens with detached entities.

**Comment by zoltish** [comment]
**Update**: This actually seems to be an issue with the `BodypartEntity` having a defined id (other than 0) even though theyre being inserted for the very first time.

**Comment by greenrobot-team** [comment]
According to the docs [you should attach the box before modifying `ToMany`](http://objectbox.io/documentation/relations/#Updating_ToMany) for entities that use `@Id(assignable = true)`.

This is tracked internally as open-source issue 38.
-ut

**Comment by wb1992321** [comment]
@greenrobot-team 
@greenrobot 
ToMany has too many problems, I am almost going to collapse.

**Comment by willks** [comment]
> @greenrobot-team
> @greenrobot
> ToMany has too many problems, I am almost going to collapse.

Yes it's bloody nasty. One of the worst implementations for a "one-to-many" out there. The fact you need a "TooMany" type to pollute your model means the project has already lost the goal of being simple, without even running the race!

Have you tried Couchbase Mobile? 10000x easier - you just save your document, like MongoDb. It literally eats ObjectBox and RealmDb from a simplicity standpoint - but it's slower than both and doesn't support multi-document transactions. I need transactions so I'm still banging my head against the wall with BrokenBox.

Still it's free - and you get what you pay for I guess :)
