### ISSUE TITLE
getAndroidFileDir() error

### ISSUE THREAD

**Issue by xieyingwu** [objectbox/objectbox-java#491]
When i create the dbTable, invoke the method created by code 
`BoxStore boxStore = MyObjectBox.builder().name(dbName).androidContext(IhApplication.getContext()).build();`
i got a crash,
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.govee.home/com.govee.home.device.ui.DeviceDetailActivity}: java.lang.IllegalStateException: Android files dir does not exist
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2725)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2786)
     at android.app.ActivityThread.-wrap12(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:173)
     at android.app.ActivityThread.main(ActivityThread.java:6459)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
  Caused by: java.lang.IllegalStateException: Android files dir does not exist
     at io.objectbox.BoxStoreBuilder.getAndroidFilesDir(BoxStoreBuilder.java:224)
     at io.objectbox.BoxStoreBuilder.getAndroidBaseDir(BoxStoreBuilder.java:202)
     at io.objectbox.BoxStoreBuilder.androidContext(BoxStoreBuilder.java:177)
```

i do not understand why the getFilesDir() dir not exist,

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue. -ut

**Comment by ghostteamo** [comment]
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6914)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:239)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2059)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:238)
  at android.app.ActivityThread.main (ActivityThread.java:7897)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ChildZygoteInit.runZygoteServer (ChildZygoteInit.java:136)
  at com.android.internal.os.WebViewZygoteInit.main (WebViewZygoteInit.java:147)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:998)
Caused by: java.lang.IllegalStateException: 
  at io.objectbox.BoxStoreBuilder.getAndroidFilesDir (BoxStoreBuilder.java:274)
  at io.objectbox.BoxStoreBuilder.getAndroidBaseDir (BoxStoreBuilder.java:252)
  at io.objectbox.BoxStoreBuilder.androidContext (BoxStoreBuilder.java:202)
  at com.oneplus.store.context.initializer.CacheApplicationInitializer.objectBoxInitialize (CacheApplicationInitializer.kt:48)
  at com.oneplus.store.context.initializer.CacheApplicationInitializer.initialize (CacheApplicationInitializer.kt:32)
  at io.ganguo.core.context.BaseApp.onCallApplicationInitializer (BaseApp.kt:73)
  at io.ganguo.core.context.BaseApp.onCreate (BaseApp.kt:60)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6909

**Comment by ghostteamo** [comment]
![image](https://user-images.githubusercontent.com/13637659/116380516-9ec7bf80-a846-11eb-9d29-b2ae641c68bc.png)
