### ISSUE TITLE
DbException: ObjectBox can not create directory

### ISSUE THREAD

**Issue by casadogg** [objectbox/objectbox-java#574]
## Issue Basics
- ObjectBox version (are using the latest version?): 2.1.0
- Reproducibility: always

### Description
Tested on a physical device (Motorola G6 Play - Android 8.0) and on an emulator (Samsung Galaxy S7 - Android 7.1.1), both Android O.

It happens when I try to build a BoxStore with a provided directory (name doesn't matter) in an android instrumentation test.

### Code

```
private val TEST_DIRECTORY = File("objectbox")

abstract class BaseObjectBoxTest : BaseTest() {
    var store: BoxStore? = null

    @Before
    fun setUpStore() {
        BoxStore.deleteAllFiles(TEST_DIRECTORY)

        store = MyObjectBox.builder().run {
            directory(TEST_DIRECTORY)
            debugFlags(DebugFlags.LOG_QUERIES or DebugFlags.LOG_QUERIES)
            build()
        }
    }

    @After
    fun tearDown() {
        store?.close()
        store = null
        BoxStore.deleteAllFiles(TEST_DIRECTORY)
    }
}
```

### Logs & stackstraces
```
io.objectbox.exception.DbException: Could not create directory: /objectbox
at io.objectbox.BoxStore.getCanonicalPath(BoxStore.java:245)
at io.objectbox.BoxStore.<init>(BoxStore.java:192)
at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:352)
at com.loggi.client.common.objectbox.BaseObjectBoxTest.setUpStore(BaseObjectBoxTest.kt:23)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```

## Entities
Does not apply

## Misc
Nothing special, just a simple android instrumentation test.

**Comment by greenrobot-team** [comment]
The instrumentation tests run on Android and the test app does not have its own app folder. We internally work around this by creating a folder in the directory of the app under test, like:

```java
    @NonNull
    private File getObjectBoxTestDir() {
        // the test app does not have app directories
        // so write to the directories of the app under test,
        // but in a different folder to avoid conflicts with the app
        File targetFilesDir = InstrumentationRegistry.getTargetContext().getFilesDir();
        return new File(targetFilesDir, "objectbox-test");
    }
```
-ut

**Comment by casadogg** [comment]
@greenrobot-team Huh, that was the problem. Should have paid more attention to the fact that the test app runs differently.

Thanks a lot :-)
