### ISSUE TITLE
ClassNotFoundException: Didn't find class "long"

### ISSUE THREAD

**Issue by Flo354** [objectbox/objectbox-java#582]
## Issue Basics
- ObjectBox version (are using the latest version?): 2.2.0 (not present in 2.1.0)
- Reproducibility: always

### Description
When sending my serializable entity within an intent to send it to another Activity, the app crash throwing a ClassNotFoundException for the class "long" 

### Code
```java
@Entity
public class Address implements Serializable {

    @Id
    private Long id;

    @Convert(converter = UUIDConverter.class, dbType = String.class)
    private UUID uuid;

    private ToOne<Profile> profile;

    @Index
    private boolean defaultAddress;

    private String name;

    private String addressLine1;

    private String addressLine2;

    private String addressLine3;

    private String zipCode;

    private String city;

    private String countryCode;

    @Convert(converter = TypeConverter.class, dbType = String.class)
    private Type type;

    @Convert(converter = PhoneNumberConverter.class, dbType = String.class)
    private Phonenumber.PhoneNumber phoneNumber;

    // COMPANY FIELDS

    private String status;

    private String companyName;

    private String vatNumber;

    // TRANSIENTS

    @Transient
    private AddressValidator validator;

    //...

    public enum Type {
        INDIVIDUAL(R.string.AddressCreation_individual), COMPANY(R.string.AddressCreation_company);

        private int translation;

        Type (int translation) {
            this.translation = translation;
        }

        public int getTranslation() {
            return translation;
        }

        public String getTranslation(Context context) {
            return context.getResources().getString(translation);
        }

        public static Type fromString(String value) {
            for (Type enumValue: values()) {
                if (enumValue.toString().equalsIgnoreCase(value)) {
                    return enumValue;
                }
            }

            return null;
        }
    }

    //...
}
```

```java
        Intent intent = new Intent(getActivity(), AuthenticatedActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        intent.putExtra(AddressController.SHIPPING_ADDRESS, shippingAddress);

        startActivity(intent);
        getActivity().finish();
```

### Logs & stackstraces
```
2018-10-11 18:41:34.093 20874-20874/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2018-10-11 18:41:34.093 20874-20874/? E/libpersona: scanKnoxPersonas
2018-10-11 18:41:36.789 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:37.977 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:38.564 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:40.585 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:40.597 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:48.048 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:49.969 20874-20874/com.test E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-11 18:41:50.015 20874-20874/com.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test, PID: 20874
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test/com.test.activities.AuthenticatedActivity}: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.test.models.Address)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.test.models.Address)
        at android.os.Parcel.readSerializable(Parcel.java:2957)
        at android.os.Parcel.readValue(Parcel.java:2743)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3059)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.BaseBundle.getBoolean(BaseBundle.java:825)
        at android.content.Intent.getBooleanExtra(Intent.java:7573)
        at com.facebook.appevents.internal.SourceApplicationInfo$Factory.create(SourceApplicationInfo.java:127)
        at com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated(ActivityLifecycleTracker.java:133)
        at com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated(ActivityLifecycleTracker.java:79)
        at android.app.Application.dispatchActivityCreated(Application.java:221)
        at android.app.Activity.onCreate(Activity.java:1067)
        at android.support.v4.app.SupportActivity.onCreate(ComponentActivity.java:75)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:335)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
        at com.test.activities.AuthenticatedActivity.onCreate(AuthenticatedActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.ClassNotFoundException: long
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel$2.resolveClass(Parcel.java:2943)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
        at java.io.ObjectInputStream.readClass(ObjectInputStream.java:1487)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1337)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2003)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1927)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1804)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2003)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1927)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1804)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2003)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1927)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1804)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
2018-10-11 18:41:50.016 20874-20874/com.test E/AndroidRuntime:     at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2003)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1927)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1804)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
        at android.os.Parcel.readSerializable(Parcel.java:2951)
        	... 26 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "long" on path: DexPathList[[zip file "/data/app/com.test-Sz5PzieEAvFM1w_xohMXhg==/base.apk"],nativeLibraryDirectories=[/data/app/com.test-Sz5PzieEAvFM1w_xohMXhg==/lib/arm64, /data/app/com.test-Sz5PzieEAvFM1w_xohMXhg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 51 more
```

## Misc
I suspect the `ToOne` attribute causing this

**Comment by abdurahmanadilovic** [comment]
You don't need to send the whole object in the intent's argument. You only need the DB id and you can fetch your model in the next activity from the database. Avoid putting lot of things in the bundle because you can get an exception on newer Android versions.

**Comment by Flo354** [comment]
Hi,

I am aware of that, but sometimes I can't do that, since sometimes my object are not saved in database.
These objects are actually addresses, but in case of guest checkout, the address is not saved within the database and must not be saved in the database. So I have to send the object through the intent. 

And this was working fine until 2.1.0.

**Comment by abdurahmanadilovic** [comment]
I would advise you to store everything in a database, create a new model called Guests and store it in the database. Once you don't need that data anymore delete it from the DB. The reason I advise you to do that is because if your activity is in the background long enough Android will kill your app but keep your activity stack, that means in onCreate your bundle will be empty and you won't be able to show the user any content.

 If you really want to just pass a model through a bundle then create a new model that is not your DB model and a converter that can convert between the two models. So the flow will be like this DBModel -> converter -> BundleModel -> Activity -> BundleModel. Then use the bundle model.

Also I noticed you are doing this "getActivity().finish()" after you start an activity. Don't do that, if you don't want that activity in the stack just put in the manifest noHistory=true for that activity and Android will not keep your activity on the activity stack.

**Comment by greenrobot-team** [comment]
@abdurahmanadilovic Thanks.

This is #342, an issue with Android code outside of our control. Check my comment there: https://github.com/objectbox/objectbox-java/issues/342#issuecomment-372311310

In short and as was already said: do not pass entities through intents. Instead save them to the database, then only pass the ID.
-ut

**Comment by Flo354** [comment]
Hi there,

I am sorry for my late answer. Didn't have time to read the answers.
Ok, I understand your opinion and I understand that it is a better practice, so I will follow the path.

However, I still don't understand why did it work until 2.1.0 and suddenly not working in 2.2.0 with no reference of a change like this in the changelog?
