### ISSUE TITLE
Box.get(id) crashes with DbException: STD out of range: vector

### ISSUE THREAD

**Issue by Gaket** [objectbox/objectbox-java#606]
## Issue Basics
- ObjectBox version (are using the latest version?): 2.1.0
- Reproducibility: occures one user devices, can't reproduce it

### Description
Crash when trying to get an entity

### Code
```
@NonNull
  Contact updateBaseContact(@NonNull Contact contactFromAndroid) {
    Contact contactFromDb = getContactFromDb(contactFromAndroid);
    if (contactFromDb != null) {
      // Update all the field that are stored in Android framework db and could be changed
      updateContactBaseFields(contactFromAndroid, contactFromDb);
      contactBox.put(contactFromDb);
      return contactFromDb;
    } else {
      long id = contactBox.put(contactFromAndroid);
      return contactBox.get(id);
    }
  }
```

### Logs & stackstraces
```
Caused by io.objectbox.exception.DbException: STD out of range: vector
       at io.objectbox.Cursor.nativeGetEntity(Cursor.java)
       at io.objectbox.Cursor.get(Cursor.java:151)
       at io.objectbox.Box.get(Box.java:192)
       at com.vyng.android.contacts.ContactsDao.updateBaseContact(ContactsDao.java:75)
       at com.vyng.android.contacts.ContactManager.updateCachedContactBase(ContactManager.java:231)
       at com.vyng.android.contacts.ContactManager.updateCachedContactBase(ContactManager.java:222)
       at com.vyng.android.contacts.-$$Lambda$gZ9-qoMdLQJxHocDycVdeUuKYRo.accept(lambda)
       at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:54)
       at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
       at io.reactivex.Single.subscribe(Single.java:3438)
       at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
       at io.reactivex.Single.subscribe(Single.java:3438)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

## Entities
```
@Entity
public class Contact {
  ToOne<Channel> channelToOne;
  @Id(assignable = true)
  private long id;
  private String contactId;
  @Index
  private String formattedPhone;
  @Index
  private String displayName;
  private String displayPhone;
  private String contactType;
  private String photoUri;
  private String fullPhotoUri;
  private boolean showPostCallWidget = true;
  private int callsFromContact;
  private long lastCallDate = 0L;
  @Index
  private String lookupKey;
  private boolean hasVyngApp = false;
  private int appVersionCode = -1;
  private boolean sharedRingtoneSyncStarted = false;

  @Transient
  transient PhoneUtils phoneUtils;

 // Constructor, getter, setters
}
```

## Misc
We had this issue on ObjectBox 0.9.15, 1.2.1 and we continue to have it after upgrading to 2.1.0

**Comment by greenrobot-team** [comment]
Thanks, though if you can't reproduce this, we probably can't either.

For potential reproduction:
- entity uses `@Id(assignable = true)`
- entity put, then immediately get by id
  - [ ] compare against error message for non-existing entity id

Possibly related (only error message is the same):
#151 (no response)
#192 
-ut

**Comment by greenrobot-team** [comment]
Tried to reproduce using `2.2.0` and some obvious things like negative IDs, reserved ID `-1`, max and min long. Also in a loop and with `String` index. No luck.

Leaving open if anybody else can share code to reliably reproduce.
-ut

**Comment by Gaket** [comment]
Btw, in the same Crashlytics issue we see in logs another case. I don't think it is bound to this one, but let's see.

We have `IllegalArgumentException: Illegal key value: 18446744073709551615` in our logs. The strange thing is that `setId()` is used only in conjuction with getting another object from db, with a similar pattern to the one above:
```
Channel channel = getChannelFromObjectBox();
anotherChannel.setId(channel.getId());
// update some fields of the channel, don't touch the id
channelBox.put(anotherChannel);
```

Is it possible that a queried object has `-1` as an id? I'll double check it, but for now this seems the only possible case. Maybe, there are some concurrency issues from our side?

**Comment by Gaket** [comment]
Recently we got some new spike of the errors. It looks like it happened the same time when we missed an error leading to OOM errors in the app. May this "STD out of range: vector" is bound to the overall OOM error?

`Caused by io.objectbox.exception.DbException: STD out of range: vector
       at io.objectbox.query.Query.nativeFind(Query.java)
       at io.objectbox.query.Query$3.call(Query.java:130)
       at io.objectbox.query.Query$3.call(Query.java:127)
       at io.objectbox.Box.internalCallWithReaderHandle(Box.java:627)
       at io.objectbox.query.Query.find(Query.java:127)
       at com.vyng.android.video.cache.VideoCacheServiceHelper.getChannelsWhichMustBeCachedForContacts(VideoCacheServiceHelper.java:103)
       at com.vyng.android.video.cache.CacheWatcher.lambda$actualizeAndAddToWatchList$2(CacheWatcher.java:105)
       at com.vyng.android.video.cache.CacheWatcher$$Lambda$3.apply(Unknown Source)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:262)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:559)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
       at com.vyng.android.video.cache.VideoCacheServiceHelper.lambda$clearBrokenMediasCache$0(VideoCacheServiceHelper.java:66)
       at com.vyng.android.video.cache.VideoCacheServiceHelper$$Lambda$1.subscribe(Unknown Source)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:11442)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
       at com.vyng.android.video.cache.VideoCacheServiceHelper.lambda$getAllCachedMediasObservable$1(VideoCacheServiceHelper.java:84)
       at com.vyng.android.video.cache.VideoCacheServiceHelper$$Lambda$2.subscribe(Unknown Source)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:11442)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:11442)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:11442)
       at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
       at io.reactivex.Observable.subscribe(Observable.java:11442)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)`

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Feel free to re-open with more details or submit a new issue if the latest release is still affected.
