### ISSUE TITLE
No schema set on store

### ISSUE THREAD

**Issue by hetang** [objectbox/objectbox-java#619]
Hi Team,

I am facing below issue only in production for few devices. I have tested in my personal and emulator and never faced this issue. Not sure how to reproduce and fix. Please Please help me here.

```
Fatal Exception: io.objectbox.exception.DbException: No schema set on store
       at io.objectbox.query.QueryBuilder.nativeCreate(QueryBuilder.java)
       at io.objectbox.query.QueryBuilder.(QueryBuilder.java:168)
       at io.objectbox.Box.query(Box.java:546)
       at com.tripactions.data.net.responses.account.TripInfoKt.getUpcomingActiveTripInfoQuery(TripInfo.kt:136)
       at com.tripactions.data.net.responses.account.TripInfoKt.getUpcomingActiveTripInfo(TripInfo.kt:97)
       at com.tripactions.alpha.mytrips.presenters.TripInfoPresenter.getCachedUpcomingTrips(TripInfoPresenter.kt:87)
       at com.tripactions.alpha.mytrips.activities.MyTrips.onStart(MyTrips.kt:153)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
       at android.app.Activity.performStart(Activity.java:6915)
       at android.app.Activity.performRestart(Activity.java:6974)
       at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4817)
       at android.app.ActivityThread.access$1500(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1828)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

## Issue Basics
- ObjectBox version (are using the latest version?): *2.0.0-beta*
- Reproducibility: *occasionally without visible pattern*

### Description
*Happening only on samsung devices with OS version 6.0.1, 7.0 & 8.0*

Please suggest, if you need code sample. I will share private gist with you.

Thanks

**Comment by greenrobot-team** [comment]
First of all, please try if updating to `2.2.0` resolves the issue. There have been many improvements.

cc @greenrobot Then I have never seen `DbException: No schema set on store`, can you say more about this?

-ut

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
