### ISSUE TITLE
io.objectbox.exception.DbException: DB's last index ID 3 is higher than 1 from model

### ISSUE THREAD

**Issue by fly904021125** [objectbox/objectbox-java#622]
## Issue Basics
- ObjectBox version (are using the latest version?): *2.1.0*
- Reproducibility: *[ occasionally without visible pattern ]*

### Description
When I initialize the objectbox using 
MyObjectBox.builder().androidContext(this).buildDefault()

then it throw the exception,but sometimes it works fine.

### Logs & stackstraces
Caused by: io.objectbox.exception.DbException: DB's last index ID 3 is higher than 1 from model
        at io.objectbox.BoxStore.nativeCreate(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:195)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:352)
        at io.objectbox.BoxStoreBuilder.buildDefault(BoxStoreBuilder.java:396)

**Comment by fly904021125** [comment]
Can any one explain what the exception means?

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
