### ISSUE TITLE
 io.objectbox.exception.DbFullException:

### ISSUE THREAD

**Issue by Xujun770366270** [objectbox/objectbox-java#623]
E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.xujun.db.dbtest, PID: 7195
    io.objectbox.exception.DbFullException: Could not put (error code -30792)
        at io.objectbox.Cursor.collect313311(Native Method)
        at com.xujun.db.dbtest.VitalDataBeanaCursor.put(VitalDataBeanaCursor.java:87)
        at com.xujun.db.dbtest.VitalDataBeanaCursor.put(VitalDataBeanaCursor.java:16)
        at io.objectbox.Box.put(Box.java:407)
        at com.xujun.db.dbtest.MainActivity.ObjectBoxAddDataa(MainActivity.java:320)
        at com.xujun.db.dbtest.MainActivity.access$900(MainActivity.java:86)
        at com.xujun.db.dbtest.MainActivity$16.run(MainActivity.java:632)
        at java.lang.Thread.run(Thread.java:761)
I/Process: Sending signal. PID: 7195 SIG: 9

 if my  Database exceeds 1G ,I not  put data

**Comment by wizardmly** [comment]
same to thread https://github.com/objectbox/objectbox-java/issues/295
