### ISSUE TITLE
ToMany Collections.sort(comparator) not get called

### ISSUE THREAD

**Issue by eduvm** [objectbox/objectbox-java#632]
## Issue Basics
- ObjectBox version: 2.2.0
- Reproducibility: always

### Description
The Comparator that is seted in the ToMany list is never called.

    @Entity
    class Pedido() : Serializable {
    
        @Id
        var id: Long = 0
    
         lateinit var listaItens: ToMany<ItemPedido>
    
        init {
    
            listaItens.setComparator(object : Comparator<ItemPedido> {
    
                override fun compare(o1: ItemPedido, o2: ItemPedido): Int {
    
                    return o2.i_ordem - o1.i_ordem
    
                }
    
            })
    
        }
    
    }

I think the problem is because the "entities" in the ToMany class is never null to call

    Collections.sort(newEntities, comparator);

ToMany.java

    private void ensureEntities() {
        if (entities == null) {
            ...
                if (comparator != null) {
                    Collections.sort(newEntities, comparator);
                }
             ...
    }

**Comment by greenrobot-team** [comment]
It should get called once you access the `ToMany`, for example with `listaItens[0]` or `listaItens.add(entity)`. When the entities are initially loaded from the database the comparator is used.

Can you share an example where you would expect the comparator to be called but it is not?
-ut

**Comment by eduvm** [comment]
I am using like this:

    @Entity
    class Pedido() : Serializable {

        @Id
        var id: Long = 0

         lateinit var listaItens: ToMany<ItemPedido>

        init {

            listaItens.setComparator(object : Comparator<ItemPedido> {

                override fun compare(o1: ItemPedido, o2: ItemPedido): Int {

                    return o2.i_ordem - o1.i_ordem

                }

            })

        }

    }

So i initialize the pedido object:

    val pedido = Pedido()

Then i create the RecyclerView adapter with the pedido.listaItens
Then i start adding itens:

    val item1 = ItemPedido();

    item1.ordem = 1

    pedido.listaItens.add(item1)

    adapter.notifyDataSetChanged()

    val item2 = ItemPedido()

    item2.ordem = 2

    pedido.listaItens.add(item2)

    adapter.notifyDataSetChanged()

So, if the comparator worked correctly I would have

    - item2
    - item1

But i am getting

    - item1
    - item2

Sorry, my english is not so good and i tried to explain the better possible.

I also tried to debug the ToMany.java, that is wy i said that the Comparator is never called.

There is something that i can try?

**Comment by eduvm** [comment]
No, i can't;

The reason why i tried to use a comparator in the inicialization of the ToMany object is because when i try to use a Collection.sort i get the error:

    Process: br.com.eduvm.mastervendascliente, PID: 14008
    java.lang.UnsupportedOperationException
        at java.util.concurrent.CopyOnWriteArrayList$COWIterator.set(CopyOnWriteArrayList.java:1120)
        at java.util.List.sort(List.java:504)
        at java.util.Collections.sort(Collections.java:201)

**Comment by greenrobot-team** [comment]
Ah, you should have led with that ;)

In this case you can exchange the `List` implementation the `ToMany` uses from a `CopyOnWriteArrayList` with for example an `ArrayList`:
```
val pedido = Pedido()
pedido.listaItens.setListFactory(new ArrayListFactory());
// now add items
...
// and sort them
Collections.sort(pedido.listaItens, mComparator);
```

However, the list factory is only used if the entity that has the `ToMany` has not been persisted, yet (`id == 0`).

So this **won't work** for entities you get from the database, like:
`val pedido = box.get(pedidoId)`

Does that help?

-ut
