### ISSUE TITLE
java.lang.IllegalStateException: Illegal reader TX

### ISSUE THREAD

**Issue by carotkut94** [objectbox/objectbox-java#640]
## Issue Basics
- ObjectBox v2.2.0
- Reproducibility: always

### Description
In my app i have a logout functionality in which, If user presses logout, then all of user data will be deleted
using 
```
boxStore.close();
boxStore.deleteAllFiles();
sharedPreferences.edit().clear().apply();
```` 
and user will be taken to the splash screen then to the login screen, if user login is successful the home screen comes up in which i have to show recent data, if not null.
but when i begin to read the data from object box it gives
```
java.lang.RuntimeException: Unable to resume activity {com.iprivato.privato/com.iprivato.privato.MainActivity}: java.lang.IllegalStateException: Illegal reader TX state
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3919)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3951)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Illegal reader TX state 

```
### Code
recentChatModelBox.getAll();

### Logs & stackstraces
```
java.lang.RuntimeException: Unable to resume activity {com.iprivato.privato/com.iprivato.privato.MainActivity}: java.lang.IllegalStateException: Illegal reader TX state
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3919)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3951)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Illegal reader TX state 

```
and the app crashes

But if i open it up again (I mean restart completely after crash), it works fine. All of my instances are singleton, and injected using dagger.

**Comment by greenrobot-team** [comment]
Thanks. Could you please share the full stack trace? The interesting part is after the `Caused by:` line.

In general and if you are truly using singletons: be aware that after calling `boxStore.close()` you can no longer use `boxStore`. You will have to build a new instance using `MyObjectBox.builder()`.

Though there can still be issues with threads that continue to use the `BoxStore`.

Maybe as an alternative you could use `box.removeAll()`? That does not require deleting the database files.
-ut

**Comment by carotkut94** [comment]
the complete stacktrace is 
````
2019-01-14 23:47:44.511 26528-26528/com.iprivato.privato E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iprivato.privato, PID: 26528
    java.lang.RuntimeException: Unable to resume activity {com.iprivato.privato/com.iprivato.privato.MainActivity}: java.lang.IllegalStateException: Illegal reader TX state
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3919)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3951)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Illegal reader TX state
        at io.objectbox.Box.getReader(Box.java:77)
        at io.objectbox.Box.getAll(Box.java:321)
        at com.iprivato.privato.database.datamanager.RecentChatManager.getAllRecentMessages(RecentChatManager.java:33)
        at com.iprivato.privato.fragments.Chat.reloadAndNotify(Chat.java:83)
        at com.iprivato.privato.fragments.Chat.onResume(Chat.java:77)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7330)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3911)

````

I cannot go with box.removeAll() as i will need to do this for every box i have created.

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
