### ISSUE TITLE
Could not open env for DB (35) (error code 35)

### ISSUE THREAD

**Issue by Eason2Wang** [objectbox/objectbox-java#663]
*Before creating a new issue, make sure that you checked: (1) existing issues, (2) docs (3) FAQ.
TEMPLATE FOR ISSUES ONLY - for feature requests just delete the text and start fresh.
Please help us to fix issues asap: this template reduces checking with you back and forth.
Replace italic sections with your input.
For __support questions__, please use [stackoverflow with the [objectbox] tag](https://stackoverflow.com/questions/tagged/objectbox) - we get notified.*

## Issue Basics
- ObjectBox version (are using the latest version?): *2.1.0*
- Reproducibility: *occasionally without visible pattern*

### Description
*It seems the exception will occur on some users who install my app for the first time.*

### Code
*boxStore = MyObjectBox.builder().androidContext(this).build();
        if (BuildConfig.DEBUG) {
            new AndroidObjectBrowser(boxStore).start(this);
        }*

### Logs & stackstraces
*java.lang.RuntimeException: Unable to create application com.tozmart.commonsdk.core.MyApplication: io.objectbox.exception.DbException: Could not open env for DB (35) (error code 35)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6586)
	at android.app.ActivityThread.access$1900(ActivityThread.java:267)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: io.objectbox.exception.DbException: Could not open env for DB (35) (error code 35)
	at io.objectbox.BoxStore.nativeCreate(Native Method)
	at io.objectbox.BoxStore.<init>(BoxStore.java:195)
	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:352)
	at com.tozmart.commonsdk.core.MyApplication.onCreate(MyApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6566)*

## Entities
*Provide the code for entities related to the bug (shorten to relevant parts).*

## Misc
*Is there anything special about your app?
May transactions or multi-threading play a role?
Did you find any workarounds to prevent the issue?*

**Comment by greenrobot-team** [comment]
This is a Linux kernel error code, this likely is not an ObjectBox issue.

`EDEADLK		35	/* Resource deadlock would occur */`
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno.h#L7

-ut

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
