### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError couldn't find "libobjectbox-jni.so"

### ISSUE THREAD

**Issue by eduvm** [objectbox/objectbox-java#671]
## Issue Basics
- ObjectBox version: 2.3.3
- Reproducibility: occasionally without visible pattern

```
MainApplication.kt

    // Inicializa ObjectBox
    mBoxStore = MyObjectBox.builder().androidContext(this).build()
```

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/br.com.eduvm.evm3umanager.ads-1/base.apk"],nativeLibraryDirectories=[/data/app/br.com.eduvm.evm3umanager.ads-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libobjectbox-jni.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
       at java.lang.System.loadLibrary(System.java:1562)
       at io.objectbox.internal.NativeLibraryLoader.(NativeLibraryLoader.java:79)
       at io.objectbox.internal.NativeLibraryLoader.checkUnpackLib(NativeLibraryLoader.java)
       at io.objectbox.BoxStore.(BoxStore.java:197)
       at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
       at br.com.eduvm.evm3umanager.MainApplication.onCreate(MainApplication.kt:24)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by greenrobot-team** [comment]
Thanks! Try the solution suggested at https://github.com/objectbox/objectbox-java/issues/605#issuecomment-460539359.

Report your findings in #605. Closing this as duplicate.
-ut
