### ISSUE TITLE
Crash : NativeLibrary not found

### ISSUE THREAD

**Issue by samjith** [objectbox/objectbox-java#680]
Our project is an android system app installed to be installed in System/priv-app.

[Objectbox version being used] - '2.1.0'

On start up, app throws this exception and crashes.

03-26 17:21:59.391   806   806 E AndroidRuntime: FATAL EXCEPTION: main

03-26 17:21:59.391   806   806 E AndroidRuntime: Process: a75f.io.renatus, PID: 806

03-26 17:21:59.391   806   806 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Couldn't load objectbox from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/RENATUS_CCU_dev_1.114.0.apk", zip file "/data/data/a75f.io.renatus/code_cache/secondary-dexes/RENATUS_CCU_dev_1.114.0.apk.classes2.zip"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /system/lib/arm]]]: findLibrary returned null

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:358)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:526)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:71)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at io.objectbox.BoxStore.<init>(BoxStore.java:189)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:352)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at a75f.io.api.haystack.CCUTagsDb.init(CCUTagsDb.java:140)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at a75f.io.api.haystack.CCUHsApi.<init>(CCUHsApi.java:70)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at a75f.io.logic.Globals.initilize(Globals.java:163)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at a75f.io.logic.Globals.setApplicationContext(Globals.java:138)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at a75f.io.renatus.UtilityApplication.onCreate(UtilityApplication.java:93)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at a75f.io.renatus.RenatusApp.onCreate(RenatusApp.java:24)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4384)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:138)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:149)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5061)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:515)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)

03-26 17:21:59.391   806   806 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)

If I do an (adb install) of the app , where it is installed as normal app , it seems to work until the next reboot of the device. Then again app crashes with the same exception.

**Comment by samjith** [comment]
Not seen with latest version and Relinker

https://github.com/objectbox/objectbox-java/issues/605#issuecomment-460539359
