### ISSUE TITLE
The application compiled after replacing the computer runs error.

### ISSUE THREAD

**Issue by Reginer** [objectbox/objectbox-java#716]
The code hasn't changed.
The application runs for a period of time.That is to say, there are database files.
The application compiled after replacing the computer runs error.
``` 
java.lang.RuntimeException: Unable to create application win.regin.mdm.MdmApp: io.objectbox.exception.DbException: Incoming entity ID 6:7588391715842286065 does not match existing UID 8342768410595399988
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5770)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: io.objectbox.exception.DbException: Incoming entity ID 6:7588391715842286065 does not match existing UID 8342768410595399988
        at io.objectbox.BoxStore.nativeCreate(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:203)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
        at win.regin.mdm.base.core.datebase.BoxManager.init(BoxManager.java:19)
        at win.regin.mdm.base.AppMdm.onCreate(AppMdm.kt:26)
        at win.regin.mdm.MdmApp.onCreate(MdmApp.kt:20)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5767)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 
```

**Comment by Reginer** [comment]
If it's the same computer, the application works well.

**Comment by Reginer** [comment]
It turned out that default.json had changed.

**Comment by greenrobot-team** [comment]
Yes, make sure to commit `default.json` to version control.
https://docs.objectbox.io/getting-started#model-file

Maybe you can restore it from the `MyObjectBox` class, but that is tedious work.
