### ISSUE TITLE
/io.objectbox.example E/AndroidRuntime: FATAL EXCEPTION: main     Process: io.objectbox.example, PID: 20562     java.lang.RuntimeException: Unable to create application io.objectbox.example.App: io.objectbox.exception.DbException: DB's last entity ID 3 is higher than 2 from model

### ISSUE THREAD

**Issue by zxpgo** [objectbox/objectbox-java#724]
06-19 09:10:38.429 20562-20562/io.objectbox.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.objectbox.example, PID: 20562
    java.lang.RuntimeException: Unable to create application io.objectbox.example.App: io.objectbox.exception.DbException: DB's last entity ID 3 is higher than 2 from model
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4721)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.access$1500(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5421)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: io.objectbox.exception.DbException: DB's last entity ID 3 is higher than 2 from model
        at io.objectbox.BoxStore.nativeCreate(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:195)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:352)
        at io.objectbox.example.ObjectBox.init(ObjectBox.java:16)
        at io.objectbox.example.App.onCreate(App.java:12)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4717)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5421) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
06-19 09:10:38.429 3358-4304/? E/Xposed: java.io.FileNotFoundException: No such file or directory during stat() on /data/AppsSwitch.json
        at de.robv.android.xposed.services.BaseService.throwCommonIOException(BaseService.java:170)
        at de.robv.android.xposed.services.BinderService.readFile(BinderService.java:143)
        at de.robv.android.xposed.services.BinderService.readFile(BinderService.java:89)
        at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:132)
        at cn.forgiveher.appdebuggable.Xposed.Main$handleLoadPackage$1.afterHookedMethod(Main.kt:35)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
        at com.android.server.pm.PackageManagerService.getPackageInfo(<Xposed>)
        at com.android.server.am.ActivityManagerService.appendDropBoxProcessHeaders(ActivityManagerService.java:12580)
        at com.android.server.am.ActivityManagerService.reportApplicationError(ActivityManagerService.java:20684)
        at com.android.server.am.ActivityManagerService.addErrorToDropBox(ActivityManagerService.java:12633)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12228)
        at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:12212)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1406)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2671)
        at android.os.Binder.execTransact(Binder.java:446)

**Comment by greenrobot-team** [comment]
See https://docs.objectbox.io/troubleshooting#dbexception-after-switching-git-branch-no-concurrent-data-model-modifications.

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Feel free to re-open with more details or submit a new issue.
