### ISSUE TITLE
Android 9.0 io.objectbox.exception.DbException: Could not begin read transaction

### ISSUE THREAD

**Issue by lookballs** [objectbox/objectbox-java#736]
io.objectbox.exception.DbException: Could not begin read transaction (another read transaction is still active on this thread) (error code -30783)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3403)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3587)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
    at android.os.Handler.dispatchMessage(Handler.java:112)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7593)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: io.objectbox.exception.DbException: Could not begin read transaction (another read transaction is still active on this thread) (error code -30783)
    at io.objectbox.BoxStore.nativeBeginReadTx(Native Method)
    at io.objectbox.BoxStore.i(BoxStore.java:379)
    at io.objectbox.BoxStore.a(BoxStore.java:714)
    at io.objectbox.BoxStore.a(BoxStore.java:662)
    at io.objectbox.query.Query.a(Query.java:280)
    at io.objectbox.query.Query.c(Query.java:143)

**Comment by greenrobot-team** [comment]
Could you share more details? When, how often and where is this code called?

Looking at the code I'm not sure how this can happen as an active read transaction is re-used for each thread.
https://github.com/objectbox/objectbox-java/blob/c9ede740daf045aaf394657c435fa40ba042afd7/objectbox-java/src/main/java/io/objectbox/BoxStore.java#L179
https://github.com/objectbox/objectbox-java/blob/c9ede740daf045aaf394657c435fa40ba042afd7/objectbox-java/src/main/java/io/objectbox/BoxStore.java#L710-L714

**Comment by greenrobot-team** [comment]
Closing because this issue is missing details. Feel free to re-open with additional details.
