### ISSUE TITLE
DbException: Could not get from cursor (-30787) (error code -30787)

### ISSUE THREAD

**Issue by FDoubleman** [objectbox/objectbox-java#742]
Hi , I use objectbox  save my data in my APP.   It worked well before,

When I started using android 8.1.0, I had a couple of problems like this:

- abnormal data loss in database tables
-  some tables in the same database not working, and some working

（当我开始在 安卓8.1.0上使用时，出现过好几次这样的问题 1、数据库表中数据异常丢失 2、同一个数据库某些表无法打开，有的表却能正常工作））

For __support questions__, please use [stackoverflow with the [objectbox] tag](https://stackoverflow.com/questions/tagged/objectbox) - we get notified.*

## Issue Basics
- ObjectBox version (are using the latest version?): 2.2.0
- Reproducibility: *[always]*

### Description
sometime I use objectbox remove() query() put() ,it occasionally have such problems   

### Code
// used 
```
// query
 fun queryCheckCarTable(taskNo: String, orderNo: String): CheckCarTable? {
        val checkCarTableBox: Box<CheckCarTable> =
                InitEngine.getInstance().boxStore.boxFor(CheckCarTable::class.java)
            // error
        return checkCarTableBox.query().run {
            equal(CheckCarTable_.taskNo, taskNo)
            equal(CheckCarTable_.orderNo, orderNo)
            build()
        }.findUnique() ?: return null
    }
    
// put 
    
```

```
 fun createCheckCarTable(taskNo: String, orderNo: String): CheckCarTable {
        val checkCarTableBox: Box<CheckCarTable> =
                InitEngine.getInstance().boxStore.boxFor(CheckCarTable::class.java)
        var checkCarTable = checkCarTableBox.query().run {
            equal(CheckCarTable_.taskNo,taskNo)
            equal(CheckCarTable_.orderNo, orderNo)
            build()
        }.findUnique()
        if (checkCarTable == null) {
            // 创建CheckCarTable
            checkCarTable = CheckCarTable(taskTable.taskNo, taskTable.orderNo)
            ...
            // error
            mCheckCarTableId = checkCarTableBox.put(checkCarTable)
        } else {
           ...
        }
        return checkCarTable
    }
```

### Logs & stackstraces

first
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.taoche.cardetection/com.taoche.check.business.NewCheckActivity}: io.objectbox.exception.DbException: Could not get from cursor (-30797) (error code -30797)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
Caused by: io.objectbox.exception.DbException: Could not get from cursor (-30797) (error code -30797)
    at io.objectbox.Cursor.nativeDeleteEntity(Native Method)
    at io.objectbox.Cursor.deleteEntity(Cursor.java:203)
    at io.objectbox.a.b(Box.java:472)
    at com.taoche.check.db.box.BoxDBManager.updateTaskTable(BoxDBManager.kt:206)
    at com.taoche.check.db.box.BoxDBManager.createCheckCarTable(BoxDBManager.kt:122)
    at com.taoche.check.business.NewCheckActivity.y(NewCheckActivity.kt:133)
    at com.taoche.check.business.NewCheckActivity.i(NewCheckActivity.kt:119)
    at com.taoche.check.business.base.CheckBaseActivity.onCreate(CheckBaseActivity.kt:56)
    at com.taoche.check.business.NewCheckActivity.onCreate(NewCheckActivity.kt:97)
    at android.app.Activity.performCreate(Activity.java:7098)
    at android.app.Activity.performCreate(Activity.java:7089)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
    ... 9 more
io.objectbox.exception.DbException: Could not get from cursor (-30797) (error code -30797)
    at io.objectbox.Cursor.nativeDeleteEntity(Native Method)
    at io.objectbox.Cursor.deleteEntity(Cursor.java:203)
    at io.objectbox.a.b(Box.java:472)
    at com.taoche.check.db.box.BoxDBManager.updateTaskTable(BoxDBManager.kt:206)
    at com.taoche.check.db.box.BoxDBManager.createCheckCarTable(BoxDBManager.kt:122)
    at com.taoche.check.business.NewCheckActivity.y(NewCheckActivity.kt:133)
    at com.taoche.check.business.NewCheckActivity.i(NewCheckActivity.kt:119)
    at com.taoche.check.business.base.CheckBaseActivity.onCreate(CheckBaseActivity.kt:56)
    at com.taoche.check.business.NewCheckActivity.onCreate(NewCheckActivity.kt:97)
    at android.app.Activity.performCreate(Activity.java:7098)
    at android.app.Activity.performCreate(Activity.java:7089)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

```

other one 

```
io.objectbox.exception.DbException: Could not get from cursor (-30787) (error code -30787)
    at io.objectbox.query.Query.nativeFindUnique(Native Method)
    at io.objectbox.query.Query$2.call(Query.java:181)
    at io.objectbox.BoxStore.a(BoxStore.java:709)
    at io.objectbox.BoxStore.a(BoxStore.java:654)
    at io.objectbox.query.Query.a(Query.java:273)
    at io.objectbox.query.Query.d(Query.java:177)
    at com.taoche.check.db.box.BoxDBManager.queryReportVersion(BoxDBManager.kt:172)
    at com.taoche.cardetection.ui.feature.auditcar.fragment.a$8.getCurrentVersion(CheckCarDBFragment.java:289)
    at com.taoche.check.c.k$a.a(ReportVersionManager.kt:97)
    at com.taoche.cardetection.ui.feature.auditcar.fragment.a.a(CheckCarDBFragment.java:285)
    at com.taoche.cardetection.ui.feature.auditcar.fragment.a.onItemChildClick(CheckCarDBFragment.java:255)
    at com.chad.library.adapter.base.BaseViewHolder$1.onClick(BaseViewHolder.java:390)
    at android.view.View.performClick(View.java:6311)
    at android.view.View$PerformClick.run(View.java:24833)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```
## Entities
```
@Entity
class CheckCarTable() {
    constructor(taskNo: String, orderNo: String) : this() {
        this.taskNo = taskNo
        this.orderNo = orderNo
    }

    @Id
    var tableId: Long = 0

    /**
     * 任务号
     */
    var taskNo: String = ""

    /**
     * 工单号
     */
    var orderNo: String = ""

    ...
}
```

## Misc
What does this exception log error code represent?  
What causes this problem, and how can it be addressed or avoided?
I find this error often appears on android version 8.1.0. 
Does this have anything to do with the android version?

Looking forward to your reply

**Comment by FDoubleman** [comment]
this link Contains .mdb files and a screenshot of the exception that appears on browser access.

[mdb And pic](https://github.com/FDoubleman/CustomView/tree/master/extra)

Hopefully that was useful. 

thanks

**Comment by greenrobot-team** [comment]
- Error -30797 is `MDB_PAGE_NOTFOUND` and described as `Requested page not found - this usually indicates corruption`. Can you reproduce how you got the database into that state? See also https://github.com/objectbox/objectbox-java/issues/646

- Error -30787 is `MDB_CURSOR_FULL` and described as `Cursor stack too deep - internal error`. Can you share the code around `com.taoche.check.db.box.BoxDBManager.queryReportVersion(BoxDBManager.kt:172)`?

In general: check that `InitEngine.getInstance().boxStore` is properly synchronized and thread-safe.

**Comment by FDoubleman** [comment]
- 1.The problem of -30797 is quite accidental and we don't know when it will happen.The problem cannot be reproduced
- 2.this is queryReportVersion() code
~~~
   fun queryReportVersion(taskNo: String, orderNo: String): String {
        val checkCarTableBox: Box<CheckCarTable> =
                InitEngine.getInstance().boxStore.boxFor(CheckCarTable::class.java)
        val checkCarTable = checkCarTableBox.query().run {
            equal(CheckCarTable_.taskNo, taskNo)
            equal(CheckCarTable_.orderNo, orderNo)
            build()
        }.findUnique()
        if (checkCarTable != null) {
            return checkCarTable.reportVersion
        }
        return ReportVersion.CURRENT_VERSION
    }
~~~

**Comment by greenrobot-team** [comment]
1. Another user indicated the Android 8.1 issue is occuring after restarting the device. https://github.com/objectbox/objectbox-java/issues/745 Could that be the case here?

2. Initialization code looks great. However, the maxSizeInKByte seems excessive (20 Gigabytes?). Are you working with gigabytes of data?

**Comment by FDoubleman** [comment]
- I'm glad to tell you that this bug hasn't come up for a long time.  
This problem often occurs with android 8.1, and has not been detected in other versions.

According to your Suggestions, we have done the following:
First: use the latest version of the database
Second: add locks to the way the database operates (as you suggest)
Third: upgrade android phone version, avoid 8.1

But I haven't ruled out which of these methods actually works.

**Comment by FDoubleman** [comment]
We used the maxSizeInKByte() setting of 20G, and at first we suspected that the database was out of memory.Obviously this is not the reason for the lack of memory.

**Comment by FDoubleman** [comment]
Thank you for your help

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
