### ISSUE TITLE
ToMany relations :NoSuchFieldException 

### ISSUE THREAD

**Issue by songchuanyang** [objectbox/objectbox-java#743]
## Issue Basics
- ObjectBox version : *2.3.3*
- Reproducibility: *[always]*

### Description
If my JavaBean uses inheritance relationships and @Entity's ID attribute, assignable = true is used, and an error will be reported when parsing and adding one-to-many relationships.

If I use assignable = false, no error will be reported.

### Code

 ```
List<CDTO> cList = new ArrayList<>();
cList.add(new CDTO(1001, "1"));
cList.add(new CDTO(1002, "2"));
cList.add(new CDTO(1003, "3"));

 ADTO ADTO = new ADTO(10, "hhhh");
ADTO.setcList(cList);

Box<A> aBox = App.getInstance().getBoxStore().boxFor(A.class);
aBox.attach(ADTO);
ADTO.cToMany.addAll(ADTO.getcList());
aBox.put(ADTO);
```

### Logs & stackstraces
```
Caused by: java.lang.NoSuchFieldException: No field __boxStore in class Lcom/sdby/lcyg/dxa/ADTO; (declaration of 'com.sdby.lcyg.dxa.ADTO' appears in /data/app/com.sdby.lcyg.dxa-zymXiJLGbZ6CrOfd1PLG0A==/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at io.objectbox.internal.ReflectionCache.getField(ReflectionCache.java:47)
        at io.objectbox.relation.ToMany.ensureBoxes(ToMany.java:141) 
        at io.objectbox.relation.ToMany.ensureEntities(ToMany.java:186) 
        at io.objectbox.relation.ToMany.ensureEntitiesWithTrackingLists(ToMany.java:157) 
        at io.objectbox.relation.ToMany.trackAdd(ToMany.java:239) 
        at io.objectbox.relation.ToMany.addAll(ToMany.java:273) 
        at com.sdby.lcyg.dxa.LauncherActivity.onCreate(LauncherActivity.java:72) 
        at android.app.Activity.performCreate(Activity.java:7054) 
        at android.app.Activity.performCreate(Activity.java:7045) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1729) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6758) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
```

## Entities
```
@Entity
class A {
    @Id(assignable = true)
    private long id;
    private String name;

    public A(String name) {
        this.name = name;
    }

    public A(long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Backlink
    ToMany<C> cToMany;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

```

```
class ADTO extends A {


    private List<CDTO> cList;

    public ADTO(String name) {
        super(name);
    }

    public ADTO(long id, String name) {
        super(id, name);
    }

    public List<CDTO> getcList() {
        return cList;
    }

    public void setcList(List<CDTO> cList) {
        this.cList = cList;
    }
}

```
```
@Entity
class C {
    @Id(assignable = true)
    private long id;
    private String name;

    public C(String name) {
        this.name = name;
    }

    public C(long id, String name) {
        this.id = id;
        this.name = name;
    }

    ToOne<A> aToOne;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

```
```
class CDTO extends C {

    public CDTO(String name) {
        super(name);
    }

    public CDTO(long id, String name) {
        super(id, name);
    }
}
```

**Comment by greenrobot-team** [comment]
In short: using subclasses that are not annotated with `@Entity` is not supported.
https://docs.objectbox.io/advanced/entity-inheritance

Details: If you create `A` with an ID other than 0 (meaning it may not be new), `cToMany` has to check whether there are already any related `C` in the database. This requires that the source class has a `__boxStore` field. This is added by the plugin, but only to classes annotated with `@Entity`.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
