### ISSUE TITLE
Nullable ToOne Id Property in Kotlin

### ISSUE THREAD

**Issue by Syafiqq** [objectbox/objectbox-java#760]
## Issue Basics
- ObjectBox version (are using the latest version?): *2.3.4*
- Reproducibility: *always*

### Description
Cannot assign a nullable type of ToOne Id Property `var userId: Long? = null`. Always throws an error, when I use primitive type `var userId: Long = 0L`, there are no problem at all.

### Code
```
noteEntity?.let { noteDao?.put(it) }
userEntity?.let { userDao?.put(it) }

noteEntity?.user?.target = userEntity
noteEntity?.let { noteDao?.put(it) }

val noteEntities = noteDao?.all
```

### Logs & stackstraces
```
io.objectbox.exception.DbException: Cannot get value for object type Relation for property userId
at io.objectbox.Cursor.nativeFirstEntity(Native Method)
at io.objectbox.Cursor.first(Cursor.java:190)
at io.objectbox.Box.getAll(Box.java:307)
at com.github.syafiqq.objectboxtest001.db.relation.NoteTest.it_should_attached_via_update(OneToOneTest.kt:98)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

### Note Entity
```
@Entity
data class Note(
    @Id var id: Long? = null,
    var text: String? = null,
    var date: Date? = null
) {
    var userId: Long? = null  // <<== Works perfectly if I use "var userId: Long = 0L"
    lateinit var user: ToOne<User>

	// rest code
}
```
### Note Entity
```
@Entity
data class User(
    @Id var id: Long? = null,
    var name: String? = null,
    var status: String? = null
) {
    @Backlink(to = "user")
    lateinit var notes: ToMany<Note>

    // rest code
}
```

## Misc
No, just learning

**Comment by greenrobot-team** [comment]
The target ID property must be of type non-nullable `Long`. Instead of `null` the value `0` is used to define there is no target.
https://docs.objectbox.io/kotlin-support#defining-relations-in-kotlin-entities (Java type `long` is non-null)

Typically (https://docs.objectbox.io/kotlin-support#defining-relations-in-kotlin-entities) you do not need to expose the target ID property of a ToOne. The plugin will create and use a virtual one.

**Comment by dalejrios** [comment]
I had that trouble too. I found a very simple solution jajaja. Just put a empty constructor in your model entity class. In my case, only with that, work perfectly. I let you here my entity class.

```
@Entity
class Message{
    @Id var id: Long = 0
    lateinit var message: String
    lateinit var contact: ToOne<Contact>

    constructor() /* Here is the solution */
    constructor(message: String, key: String){
        this.message = message
        this.key = key
    }
}
```

**Comment by greenrobot-team** [comment]
@dalejrios Your issue is unrelated. This issue is about explicitly adding a target ID property for `ToOne`.

Anyhow, closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
