### ISSUE TITLE
DbException: Could not renew tx (another read transaction is still active on this thread) (error code -30783)

### ISSUE THREAD

**Issue by fakerqu** [objectbox/objectbox-java#763]
## Issue Basics
- ObjectBox version: 2.3.4
- Reproducibility: occasionally without visible pattern

### Description
I'm now using objectbox with multi-modules, before using objectbox on my library-module it works fine, but recently the error occours in different occasions with same exceptions below. 

### Code
```java
    @Override
    protected void onResume() {
        if (GlobalVariables.bUserInfoUpdateFlag || ObjectBoxManager.getInstance().getUserEntityBox().isEmpty()) {
            loadingUerInfo();
        } else {
            reBuildFirstItem();
        }
        this.myInfoListAdapter.notifyDataSetChanged();
        super.onResume();
    }
```

### Logs & stackstraces
```java
2019-09-10 13:47:47.958 6866-6866/com.masstest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.masstest, PID: 6866
    java.lang.RuntimeException: Unable to resume activity {com.masstest/com.masstest.activity.MyInfoManagerActivity}: io.objectbox.exception.DbException: Could not renew tx (another read transaction is still active on this thread) (error code -30783)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3974)
        at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:188)
        at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:348)
        at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:774)
        at android.widget.TabHost.setCurrentTab(TabHost.java:428)
        at android.widget.TabHost.setCurrentTabByTag(TabHost.java:309)
        at com.masstest.activity.MainTabWidgetActivity$1.onCheckedChanged(MainTabWidgetActivity.java:146)
        at android.widget.RadioGroup.setCheckedId(RadioGroup.java:190)
        at android.widget.RadioGroup.access$600(RadioGroup.java:57)
        at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:375)
        at android.widget.CompoundButton.setChecked(CompoundButton.java:174)
        at android.widget.CompoundButton.toggle(CompoundButton.java:127)
        at android.widget.RadioButton.toggle(RadioButton.java:76)
        at android.widget.CompoundButton.performClick(CompoundButton.java:132)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25889)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:7116)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:532)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)
     Caused by: io.objectbox.exception.DbException: Could not renew tx (another read transaction is still active on this thread) (error code -30783)
        at io.objectbox.Transaction.nativeRenew(Native Method)
        at io.objectbox.Transaction.renew(Transaction.java:153)
        at io.objectbox.Box.getReader(Box.java:78)
        at io.objectbox.Box.count(Box.java:288)
        at io.objectbox.Box.isEmpty(Box.java:298)
        at com.masstest.activity.MyInfoManagerActivity.onResume(MyInfoManagerActivity.java:183)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7422)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3964)
        at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:188) 
        at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:348) 
        at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:774) 
        at android.widget.TabHost.setCurrentTab(TabHost.java:428) 
        at android.widget.TabHost.setCurrentTabByTag(TabHost.java:309) 
        at com.masstest.activity.MainTabWidgetActivity$1.onCheckedChanged(MainTabWidgetActivity.java:146) 
        at android.widget.RadioGroup.setCheckedId(RadioGroup.java:190) 
        at android.widget.RadioGroup.access$600(RadioGroup.java:57) 
        at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:375) 
        at android.widget.CompoundButton.setChecked(CompoundButton.java:174) 
        at android.widget.CompoundButton.toggle(CompoundButton.java:127) 
        at android.widget.RadioButton.toggle(RadioButton.java:76) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:132) 
        at android.view.View.performClickInternal(View.java:6574) 
        at android.view.View.access$3100(View.java:778) 
        at android.view.View$PerformClick.run(View.java:25889) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:7116) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:532) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867) 
```

## Entities
It seems have no relationship with my entities

**Comment by greenrobot-team** [comment]
Thanks for reporting. `Could not renew tx (another read transaction is still active on this thread)` means that somewhere else within the app an `ObjectBox` operation is still running/could not be cleaned up properly on the main thread.

Is it possible that an `ObjectBox` operation on the main thread might get interrupted within your app?

Without looking at the code I can't really say if there is an issue. Do you have a minimal example project that can somewhat reliably reproduce this?

**Comment by fakerqu** [comment]
Problem solved, copying objectbox's **.mdb file and trying to edit boxstore at the same time will cause this exception. Is there any method backing up my boxstore? 
Thank you!

**Comment by greenrobot-team** [comment]
> Is there any method backing up my boxstore?
Nothing official. It's probably better to export/import a standard format like JSON anyhow.

If you really must copy the database file, make sure to `close()` the `BoxStore` first after all operations have finished. See details at
http://objectbox.io/files/objectbox-java/current/io/objectbox/BoxStore.html#close--
