### ISSUE TITLE
LivePagedListBuilder and ObjectBoxDataSource

### ISSUE THREAD

**Issue by taihuuho** [objectbox/objectbox-java#766]
I am running into this issue when trying to apply filters to a query.
Any updates on when this will be supported?

Thanks

```
java.lang.UnsupportedOperationException: Does not yet work with a filter yet. At this point, only find() and forEach() are supported with filters.
        at io.objectbox.query.Query.ensureNoFilterNoComparator(Query.java:156)
        at io.objectbox.query.Query.find(Query.java:220)
        at io.objectbox.android.ObjectBoxDataSource.loadRange(ObjectBoxDataSource.java:93)
        at io.objectbox.android.ObjectBoxDataSource.loadInitial(ObjectBoxDataSource.java:78)
        at androidx.paging.PositionalDataSource.dispatchLoadInitial(PositionalDataSource.java:286)
        at androidx.paging.TiledPagedList.<init>(TiledPagedList.java:107)
        at androidx.paging.PagedList.create(PagedList.java:229)
        at androidx.paging.PagedList$Builder.build(PagedList.java:388)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
```

**Comment by greenrobot-team** [comment]
This message is talking about `Query.find(limit, offset)`.

I doubt filters will ever be supported for `ObjectBoxDataSource` as it would break the internal offset calculations.

Two options:
- use more specific query conditions, or
- wait for the rewrite of the Paging library where Googlers have promised to support data manipulation/transformation/filtering/etc.

**Comment by taihuuho** [comment]
@greenrobot-team Thanks for the reply. I've tried adding more specific query conditions and that worked great.
Closing this issue
