### ISSUE TITLE
After updating a large number of fields with uid, the old version upgrades to the new version and crashes

### ISSUE THREAD

**Issue by songchuanyang** [objectbox/objectbox-java#781]
After updating a large number of fields with uid, the old version upgrades to the new version and crashes.

Use version 2.3.3

Crash log
```
2019-11-09 18:31:15.375 A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 31529 (m.sdby.lcyg.fbj), pid 31529 (m.sdby.lcyg.fbj)
2019-11-09 18:31:15.495 A/DEBUG: pid: 31529, tid: 31529, name: m.sdby.lcyg.fbj  >>> com.sdby.lcyg.fbj <<<
2019-11-09 18:31:15.793 A/DEBUG:     #00 pc 000000000012c774  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #01 pc 00000000000ed628  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #02 pc 00000000000eecbc  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #03 pc 00000000000eea64  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #04 pc 00000000000ee818  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #05 pc 000000000012eeb8  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #06 pc 0000000000133294  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #07 pc 0000000000130574  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #08 pc 0000000000130228  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #09 pc 00000000000e3424  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000)
2019-11-09 18:31:15.793 A/DEBUG:     #10 pc 000000000004fc4c  /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (offset 0x7ef000) (Java_io_objectbox_BoxStore_nativeCreate+180)
2019-11-09 18:31:15.793 A/DEBUG:     #18 pc 0000000000501904  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (deleted) (io.objectbox.BoxStore.<init>+220)
2019-11-09 18:31:15.793 A/DEBUG:     #24 pc 000000000050054e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (deleted) (io.objectbox.BoxStoreBuilder.build+54)
2019-11-09 18:31:15.793 A/DEBUG:     #30 pc 000000000040d6f8  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (deleted) (com.sdby.lcyg.fbj.core.application.App.getBoxStore+36)
2019-11-09 18:31:15.793 A/DEBUG:     #36 pc 000000000040d99e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.sdby.lcyg.fbj-a8gup6QJvZXl8TNPuhuxNQ==/base.apk (deleted) (com.sdby.lcyg.fbj.core.application.App.onCreate+22)
```

If I use version 2.4.1

Crash log
```
2019-11-11 08:53:31.809 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sdby.lcyg.fbj, PID: 27624
    java.lang.RuntimeException: Unable to create application com.sdby.lcyg.fbj.core.application.App: io.objectbox.exception.DbException: STD out of range: map::at:  key not found
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6363)
        at android.app.ActivityThread.access$1300(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1837)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:7259)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
     Caused by: io.objectbox.exception.DbException: STD out of range: map::at:  key not found
        at io.objectbox.BoxStore.nativeCreate(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:205)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
        at com.sdby.lcyg.fbj.core.application.App.getBoxStore(App.java:86)
        at com.sdby.lcyg.fbj.core.application.App.onCreate(App.java:63)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6358)
        at android.app.ActivityThread.access$1300(ActivityThread.java:222) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1837) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:232) 
        at android.app.ActivityThread.main(ActivityThread.java:7259) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908) 
```

**Comment by greenrobot-team** [comment]
Thanks for reporting! Can you by chance say how many "a large number of fields" is? Or even better, do you have a project for us to reproduce this with?

**Comment by songchuanyang** [comment]
Sorry, this is my mistake.

Because I changed the name of the JavaBean, but I used the ResetID generated by the uid. When I roll back the historical version and reuse the uid, the bug will not appear.

**Comment by songchuanyang** [comment]
> Thanks for reporting! Can you by chance say how many "a large number of fields" is? Or even better, do you have a project for us to reproduce this with?

Sorry, this is my mistake.

Because I changed the name of the JavaBean, but I used the ResetID generated by the uid. When I roll back the historical version and reuse the uid, the bug will not appear.
