### ISSUE TITLE
java.lang.UnsatisfiedLinkError: io.objectbox.Transaction.nativeIsOwnerThread

### ISSUE THREAD

**Issue by hetang** [objectbox/objectbox-java#789]
- ObjectBox version: *2.3.4*
- Reproducibility: *always*

### Description
Running Junit from command line always gets below error:
```
java.lang.UnsatisfiedLinkError: io.objectbox.Transaction.nativeIsOwnerThread(J)Z

	at io.objectbox.Transaction.nativeIsOwnerThread(Native Method)
	at io.objectbox.Transaction.close(Transaction.java:103)
	at io.objectbox.BoxStore.callInReadTx(BoxStore.java:768)
	at io.objectbox.BoxStore.callInReadTxWithRetry(BoxStore.java:699)
	at io.objectbox.query.Query.callInReadTx(Query.java:289)
	at io.objectbox.query.Query.find(Query.java:202)
	at com.tripactions.data.net.responses.trips.TripInfoKt.saveTripInfo(TripInfo.kt:109)
	at com.tripactions.alpha.timeline.presenters.CacheTripTimelinePresenterTest.setUp(CacheTripTimelinePresenterTest.kt:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### Code
Running below code in the setup method of Junit test
```
        BoxStore.deleteAllFiles(TEST_DIRECTORY)
        store = MyObjectBox.builder()
                // add directory flag to change where ObjectBox puts its database files
                .directory(TEST_DIRECTORY)
                // optional: add debug flags for more detailed ObjectBox log output
                .debugFlags(DebugFlags.LOG_QUERIES or DebugFlags.LOG_QUERY_PARAMETERS)
                .build()
```

**Comment by greenrobot-team** [comment]
Are you using Robolectric? We and others have observed the same exception, but with a different message, in that case. https://github.com/objectbox/objectbox-java/issues/482

Otherwise, a small example project would really help (e.g. to see the project setup).

**Comment by hetang** [comment]
I am using Junit and its version is `4.12`. I have a very similar class 
```
@Before
    override fun setUp() {
        super.setUp()

        // delete database files before each test to start with a clean database
        BoxStore.deleteAllFiles(TEST_DIRECTORY)
        store = MyObjectBox.builder()
                // add directory flag to change where ObjectBox puts its database files
                .directory(TEST_DIRECTORY)
                // optional: add debug flags for more detailed ObjectBox log output
                .debugFlags(DebugFlags.LOG_QUERIES or DebugFlags.LOG_QUERY_PARAMETERS)
                .build()
        val tripInfo = TripInfo(uuid = "random",
                startDate = LocalDate().plusDays(4).toDate(), endDate = LocalDate().plusDays(10).toDate(),
                flightCount = 1, hotelCount = 1)
        store?.saveTripInfo(tripInfo)

        val type = object : TypeToken<List<TripItemWS>>() {}.type
        val json = assets.readAssetAsString(javaClass, "trip_item.json")
        val tripItems: List<TripItemWS> = mapper.fromJson(json, type)
        tripItems.forEach {
            val tripItemStore = TripItemsStore(it)
            store?.saveTripItemsInfo(tripItemStore)
        }
    }

@After
    fun tearDown() {
        store?.close()
        store = null
        BoxStore.deleteAllFiles(TEST_DIRECTORY);
    }
```

Its throwing error while saving the object. `store?.saveTripInfo(tripInfo)`

**Comment by hetang** [comment]
any update here?

**Comment by greenrobot-team** [comment]
@hetang Does the solution in https://github.com/objectbox/objectbox-java/issues/847#issuecomment-616324208 help?

**Comment by greenrobot-team** [comment]
Oh, sorry. The solution might actually be https://github.com/objectbox/objectbox-java/issues/805#issuecomment-573574372. Make sure that the native library versions match the Java library versions.

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
