### ISSUE TITLE
io.objectbox.exception.DbException: Could not commit tx (87)

### ISSUE THREAD

**Issue by man-pro** [objectbox/objectbox-java#795]
Hey,
does anyone have any idea what it could be and where I could keep looking?
Thank you
Manu

Version 2.4.1
Reproducibility: Always at the db-file-size near 2GB (max. size is set to 8GB)

A bit of the stacktrace:
Exception in thread "JavaFX Application Thread" io.objectbox.exception.DbException: Could not commit tx (87) (error code 87)
	at io.objectbox.Transaction.nativeCommit(Native Method)
	at io.objectbox.Transaction.commit(Transaction.java:134)
	at io.objectbox.Transaction.commitAndClose(Transaction.java:139)
	at io.objectbox.Box.commitWriter(Box.java:125)
	at io.objectbox.Box.put(Box.java:333)
	[...]

**Comment by greenrobot-team** [comment]
Linux error 87 (assuming you run your Java app on Linux) is EUSERS or "Too many users". https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno.h

I have not seen that one before, but maybe it'll help you.

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
