### ISSUE TITLE
ObjectBox, gradle, eclipse und the “magic” ToOne/ToMany-Relations

### ISSUE THREAD

**Issue by man-pro** [objectbox/objectbox-java#798]
Hey,

the Java desktop application, in which the ObjectBox is integrated, can be created in eclipse with gradle and runs without problems. 
Now I'm trying to run JUnit-tests with eclipse and I try to start the application with eclipse. Unfortunately, both works only until the first statement comes, which accesses a ToOne or ToMany element. Then an exception is thrown. What have I forgotten to specify in eclipse?
Does anyone know any advice?

Thank you very much
Manu

```
Stacktrace:
===========
Start orders and customers
Add a customer with an order (using to-one)
Exception in thread "main" java.lang.NullPointerException
   at io.objectbox.example.relation.RelationActivity.ordersAndCustomers(RelationActivity.java:52)
   at io.objectbox.example.relation.RelationActivity.onCreate(RelationActivity.java:26)
   at io.objectbox.example.relation.Main.main(Main.java:11)


	
Source RelationActivity.java (it is the relation example):
==========================================================
39 [...]
40 private void ordersAndCustomers ()
41	{
42	Box <Customer> customerBox = ObjectBox.get ().boxFor (Customer.class);
43	Box <Order>    orderBox    = ObjectBox.get ().boxFor (Order.class);
44
45	// Remove all previous object to have clear start for simplicity's sake
46	customerBox.removeAll ();
47	orderBox.removeAll ();
48
49	logTitle ("Add a customer with an order (using to-one)");
50	Customer customer = new Customer ();
51	Order    order1   = new Order ();
52	order1.customer.setTarget (customer);
53	orderBox.put (order1);
54	logOrders (orderBox, customer);
55 [...]
	
	
gradle script:
==============
buildscript
   {
   ext.objectboxVersion = '2.5.0'
   
   repositories
      {
      jcenter()
      }
      
   dependencies
      {
      classpath "io.objectbox:objectbox-gradle-plugin:$objectboxVersion"
      }
   }


plugins 
	{
	id 'java'
	id 'application'
	}

repositories 
	{
  	jcenter()
	}

dependencies 
	{
	testImplementation 'junit:junit:4.12'

	annotationProcessor "io.objectbox:objectbox-processor:$objectboxVersion"
	implementation "io.objectbox:objectbox-java:$objectboxVersion"
	
	implementation "io.objectbox:objectbox-windows:$objectboxVersion"
	implementation "io.objectbox:objectbox-linux:$objectboxVersion"
	implementation "io.objectbox:objectbox-macos:$objectboxVersion"
	}

application
	{
	mainClassName = "io.objectbox.example.relation.Main"
	}
	
eclipse 
   {
   classpath 
      {
      file 
         {
         whenMerged 
            {
            entries.findAll
               {
               it.properties.kind.equals('lib')}.each{it.entryAttributes['module'] = true
               }   
            }
         }
      }
   }

sourceSets 
   {
   main 
      {
      java 
         {
         srcDirs = [ "src/main/java", "build/generated/sources/annotationProcessor/java/main"]   
         }
      }
   }

test
   {
   testLogging.showStandardStreams = true
   }
  
apply plugin: "eclipse"		  
apply plugin: 'io.objectbox'

group 'io.objectbox.example.relation'
version 'v0.9'

```

**Comment by greenrobot-team** [comment]
For unit tests to work with relations (ToOne, ToMany) the ObjectBox byte-code transformer needs to modify the built class files before the tests run. For plain-Java projects the transform task is hooked up to the `classes` task. Maybe make sure it runs before your tests are executed.

If that won't help you need to initialize the relation fields manually. https://docs.objectbox.io/relations#initialization-magic

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue.
