### ISSUE TITLE
Crashing after v2.4.0

### ISSUE THREAD

**Issue by shripal17** [objectbox/objectbox-java#805]
## Issue Basics
- ObjectBox version v2.4.0+
- Reproducibility: always
### Description
When an ObjectBox-containing app is used as a PRIVILEGED App (resides in /system/priv-app/) and an AOSP ROM is built using that app, i have observed that libs are separately extracted in /system/priv-app/AppName/lib and this causes the below mentioned crash everytime i try to do an operation on the database (C/R/U/D)

After deleting the lib folder in /system/priv-app/AppName/ and rebooting, the issue is gone

I think this is because of the following major change in v2.4.0

> Android: the AAR libraries ship Java 8 bytecode. Your app will not build unless you upgrade com.android.tools.build:gradle to 3.2.1 or later.

The app works normally when i downgrade to ObjectBox v2.3.4

### Code
Any database operation

### Logs & stackstraces
```logcat E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.portalcomputainment.android.launcher, PID: 7913
    java.lang.UnsatisfiedLinkError: No implementation found for boolean io.objectbox.Transaction.nativeIsOwnerThread(long) (tried Java_io_objectbox_Transaction_nativeIsOwnerThread and Java_io_objectbox_Transaction_nativeIsOwnerThread__J)
        at io.objectbox.Transaction.nativeIsOwnerThread(Native Method)
        at io.objectbox.Transaction.close(Transaction.java:103)
        at io.objectbox.Transaction.commitAndClose(Transaction.java:140)
        at io.objectbox.Box.commitWriter(Box.java:125)
        at io.objectbox.Box.put(Box.java:333)
        at com.portalcomputainment.android.launcher.fragment.MainFragment$updateWallpaper$1$1.invoke(MainFragment.kt:134)
        at com.portalcomputainment.android.launcher.fragment.MainFragment$updateWallpaper$1$1.invoke(MainFragment.kt:50)
        at com.portalcomputainment.android.launcher.service.UnsplashServiceKt$getRandomPhoto$1$1.invokeSuspend(UnsplashService.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## Misc
Is there anything special about your app? - Yes, it is a system priv-app
May transactions or multi-threading play a role? - No
Did you find any workarounds to prevent the issue? - Downgrading to v2.3.4, or deleting the lib folder works

**Comment by greenrobot-team** [comment]
Thanks for reporting. I do not have any experience with system apps.

Anyhow, `Transaction.nativeIsOwnerThread` has been added in 2.4.0. https://github.com/objectbox/objectbox-java/commit/0e480e460a6d17c85769d46a4320966f826e05e6

And based on your `UnsatisfiedLinkError`, is it possible that you somehow ship an old version of the native libraries (`libobjectbox-jni.so`)? Or, as you mention deleting the native library in /system/priv-app/AppName/ helps, maybe a new and an old version at different locations?

**Comment by shripal17** [comment]
> Thanks for reporting. I do not have any experience with system apps.
> 
> Anyhow, `Transaction.nativeIsOwnerThread` has been added in 2.4.0. [0e480e4](https://github.com/objectbox/objectbox-java/commit/0e480e460a6d17c85769d46a4320966f826e05e6)
> 
> And based on your `UnsatisfiedLinkError`, is it possible that you somehow ship an old version of the native libraries (`libobjectbox-jni.so`)? Or, as you mention deleting the native library in /system/priv-app/AppName/ helps, maybe a new and an old version at different locations?

Hi

I am not manually placing any libs in /system/priv-app/AppName/, AOSP Build System automatically extracts them from the APK and places them in the appropriate location.

I will check this once again by manually placing the lib
