### ISSUE TITLE
Illegal ID Value 0 when trying to get a list of related objects

### ISSUE THREAD

**Issue by BlackReaper94** [objectbox/objectbox-java#814]
## Issue Basics
- ObjectBox version (are using the latest version?): *2.5.0*
- Reproducibility: *[always]*

### Description
*I do try to get the a list of all tracks related to a playlist following the relation example from your website (Student Teacher example). Unfortunately every time I try to get that list it throws the exception. The database should be empty currently as I called the removeAll() methods. I do check wether the playlist does exist or not before trying to get the list. I am aware that this list currently should be empty therefore no relations/objects can be found. I'm trying to get its size ( which I honestly don't know wether it is usable or not) to prevent it from doing something if no objects are avaible. It does anyways so I guess I'm doing something wrong. On startup I want to add all tracks on device in the database. I don't want to add them multiiple times so I do check wether they already exist in the database before adding them. I am new to objectbox and may have misunderstood how it works. *

### Code
*
   public ArrayList getPlaylist(String playlistName) {
        ArrayList<Track> requestedPlaylist = new ArrayList<Track>();

// This is a method which iterates over playlistBox to find the playlistEntity ID by its name
        playlistEntity = playlistBox.get(findPlaylistEntityID(playlistName));

        if (playlistEntity.trackToMany.size() != 0) {   // <-- Seems not to work as I imagine it.
            for (Track trackItem : playlistEntity.trackToMany) {
                requestedPlaylist.add(trackItem);    ////////////// <---- This line causes the error.
            }
        }
        return requestedPlaylist;
    }.
*

### Logs & stackstraces
*Process: com.example.rms_player, PID: 24450
    java.lang.IllegalArgumentException: Illegal ID value: 0
        at io.objectbox.Cursor.nativeGetEntity(Native Method)
        at io.objectbox.Cursor.get(Cursor.java:189)
        at io.objectbox.Box.get(Box.java:211)
        at com.example.rms_player.database.DatabaseHandler.getPlaylist(DatabaseHandler.java:73)).*

## Entities
*//PlaylistEntity
@Entity
public class PlaylistEntity {

    @Id
    long id;

    public String listName;

    @Backlink
    public ToMany<Track> trackToMany;

    public PlaylistEntity() {}

    public PlaylistEntity(String listName){
        this.listName = listName;
    }

    public String getListName(){
        return listName;
    }

// Track Entity
@Entity
public class Track {

    @Id
    long id;

   public String path;
   public String title;
   public double rms;

    public ToMany <PlaylistEntity> playlistEntityToMany;

    public Track(String path, String title, double rms){
        this.path = path;
        this.title = title;
        this.rms = rms;
    }
}.*

## Misc
*It does store the tracks in the database because I need to add data to the corresponding tracks
therefor I cannot use android MediaStore. So far no multithreading and no workaround found*

**Comment by BlackReaper94** [comment]
Since I am already here. Will objectbox allow me to relate to an entity multiple times?
For playlists it needs to be possible to add the same track multiple times even though these days it is rare to do so.
