### ISSUE TITLE
Fail to run app when remove entity's relationship

### ISSUE THREAD

**Issue by yeanpei** [objectbox/objectbox-java#869]
## Issue Basics
- ObjectBox version: 2.5.1
- Reproducibility: always

### Description
I have created an entity with a ToOne relationship to another entity. Now I need to remove the relationship but still maintain the column and it's data. I followed the documentation to include UID in the property and the app build successfully but I got an error when running the app.

### Code
Original:
```
@Entity
data class Attendance(
    @Id
    @NameInDb("AttendanceId")
    var id: Long = 0 {

    lateinit var employee: ToOne<Employee>
```

Change To:
```
@Entity
data class Attendance(
    @Id
    @NameInDb("AttendanceId")
    var id: Long = 0,

    @Uid(9022054346700797833L)   //uid for the column with relationship
    @NameInDb("EmpyKey")  //rename and remove relationship
    var empyKey: Long
```

default.json:

![Capture](https://user-images.githubusercontent.com/51101784/85109623-2f576b80-b244-11ea-8dac-39625cccc413.PNG)

### Logs & stackstraces
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lintramax.quartotimeattendance.qa, PID: 2918
    java.lang.RuntimeException: Unable to create application com.lintramax.quartotimeattendance.QuartoTimeAttendanceApp: io.objectbox.exception.DbException: Property employeeId (8, Relation) of entity Attendance is not compatible to its previous definition. Check its type.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6318)
        at android.app.ActivityThread.access$1400(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1834)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7212)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
     Caused by: io.objectbox.exception.DbException: Property employeeId (8, Relation) of entity Attendance is not compatible to its previous definition. Check its type.
        at io.objectbox.BoxStore.nativeCreate(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:205)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
        at com.lintramax.quartotimeattendance.db.ObjectBox.init(ObjectBox.kt:18)
        at com.lintramax.quartotimeattendance.QuartoTimeAttendanceApp.onCreate(QuartoTimeAttendanceApp.kt:20)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6313)
        at android.app.ActivityThread.access$1400(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1834) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7212) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887) 
```

**Comment by greenrobot-team** [comment]
Sorry, you can not migrate a property to another type. ObjectBox would not know how to, in this case map a Relation to a Long.
https://docs.objectbox.io/advanced/data-model-updates#changing-property-types

**Comment by yeanpei** [comment]
Is there any example to write the migration logic? 
Where should I do it? Is it right after ` ObjectBox.init(this)`

**Comment by greenrobot-team** [comment]
No example. Yes, you either do this right after you create `BoxStore`. Or your code could handle this in the getter for `Employee`, which first checks if there is a value for `employee`.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
