### ISSUE TITLE
crash on query with Entity not having no-arg constructor

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#900]
I don't see this mentioned anywhere, but with my entity class without a no-arg constructor, everytime when a query like 
`wordBox.query().equal(WordOB_.word, wordStr).build().find()`
is done, the app crashes without giving any reason.  Every frustrating - I spent the whole afternoon trying to figure out the problem.  In the end, "Evaluate Expression" (on Android Studio) on the entire expression above, gives a cause regarding the need for a no-arg constructor.

Hope this can either be documented or fixed.

**Comment by greenrobot-team** [comment]
If the app crashes there must be some error output in logcat. Can you provide e.g. an example test case where this is not the case?

**Comment by LeoK987** [comment]
I ran it in debug mode and after stepping over that statement, the app immediately crashes with a popup on phone screen saying "Unfortunately xxxx  has stopped" but nothing on the debug terminal.  This should very straightforward for your engine to verify: comment out the no-arg constructor of an Entity class then you get the crash on queries, even with "wordBox.getAll()".  If you can't reproduce it, then I will try to get some LOGCAT output.

**Comment by greenrobot-team** [comment]
Fine, tried it with a very simple entity:
```kotlin
@Entity
class Example(var text: String?) {
    @Id
    var id: Long = 0

    override fun toString(): String {
        return "$id $text"
    }
}
```

Everything works fine. I suggest you look at the [bug report issue template](https://github.com/objectbox/objectbox-java/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and give the information asked.

**Comment by LeoK987** [comment]
Thank you for verifying.

I tried your example project on github (https://github.com/objectbox/objectbox-examples) by removing the no-arg constructor and adding a query statement, and indeed, it didn't crash.

Then I went back to try my code.  I have two Entity classes.  Strangely, one doesn't crash, but the other (shown below) does.  LOGCAT doesn't seem to have any indication at time of crash.  I did a screenshot of the "Evaluate Expression" window just before the crash, which you can see below.

Then under debug, I stepped into the call of getAll(), and found the crash happens in the Cursor#first().

I can't understand what happened, any insight please?

ObjectBox version I am using is: ext.objectboxVersion = '2.7.0'

<img width="1037" alt="Screen Shot 2020-08-18 at 9 41 17 AM" src="https://user-images.githubusercontent.com/6257601/90493257-0c5d1100-e13a-11ea-8531-b084af059d3e.png">

```
@Entity
public class WordOB  {

    @Id
    long id;

    @Index
    public String word;

    public int frequency;

    // public WordOB() { }

    public WordOB(String word) {
        this.word = word;
    }
...
}

```
Box.java
```
    /**
     * Returns all stored Objects in this Box.
     * @return since 2.4 the returned list is always mutable (before an empty result list was immutable)
     */
    public List<T> getAll() {
        ArrayList<T> list = new ArrayList<>();
        Cursor<T> cursor = getReader();
        try {
            for (T object = cursor.first(); object != null; object = cursor.next()) {
                list.add(object);
            }
            return list;
        } finally {
            releaseReader(cursor);
        }
    }
```

Cursor.java
```
    public T first() {
        return (T) nativeFirstEntity(cursor);
    }

```

**Comment by greenrobot-team** [comment]
Using a clean project and the `WordOB` entity class you have given, everything works as expected.

[gh-900-no-default-constructor.zip](https://github.com/objectbox/objectbox-java/files/5090695/gh-900-no-default-constructor.zip)

Please share a minimal project that reproduces this issue.

**Comment by LeoK987** [comment]
I ran your app on two of my phones, and it doesn't behave nicely.  Here is what's happening:

on Lenovo running Android 6, the app doesn't step over line 18 of MainActivity.  See screenshot.

<img width="1009" alt="Screen Shot 2020-08-18 at 5 34 48 PM" src="https://user-images.githubusercontent.com/6257601/90542768-857d5800-e17c-11ea-89f6-ca2bc45cca0d.png">

The phone's info:

![Screenshot_20200818-173847-467](https://user-images.githubusercontent.com/6257601/90542825-a2199000-e17c-11ea-8adf-cebf86223ce8.jpg)

Once I step over that line, a popup on the phone says the app unfortunately crashed.

With the no-arg constructor back in, the app runs fine on Lenovo.

On Huawei phone running Android 9, when the debugger stops on Line 18, it doesn't stay there firmly, before my action, the debugger got disconnected from the phone.  In the debugger window, I got the text below.  However the app's UI still stays normal on the screen so one would think that it still runs, but I am not sure what's going on.  It behaves in the same way even when I have the no-arg constructor back in.

```
D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@681135a,androidx.appcompat.view.ContextThemeWrapper@e8d404e
    initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
W/boxcleanexampl: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/boxcleanexampl: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/TextView: get Display Panel Type is : 0
W/boxcleanexampl: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
D/ObjectBox: Version: 2.7.0-2020-07-30 Version (native): 2.7.0-2020-07-30
D/: [ZeroHung]zrhung_send_event: wp=257, ret=0
D/: [ZeroHung]zrhung_send_event: wp=258, ret=0
Disconnected from the target VM, address: 'localhost:8604', transport: 'socket'

```

**Comment by greenrobot-team** [comment]
Now we are getting somewhere. So this is tied to specific Android versions.

I could reproduce the crash on Android 5 (API 21) as well. However, I get a full error log in Logcat:
```
08-24 12:49:39.663 2519-2519/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.objectboxcleanexample, PID: 2519
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.objectboxcleanexample/com.example.objectboxcleanexample.MainActivity}: io.objectbox.exception.DbException: Entity is expected to have a no-arg constructor: WordOB
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: io.objectbox.exception.DbException: Entity is expected to have a no-arg constructor: WordOB
        at io.objectbox.Cursor.nativeFirstEntity(Native Method)
        at io.objectbox.Cursor.first(Cursor.java:197)
        at io.objectbox.Box.getAll(Box.java:311)
        at com.example.objectboxcleanexample.MainActivity.onCreate(MainActivity.kt:18)
```

You really should have filled out the bug report template. Then I would have had that information right at the beginning...

Not sure there is anything to fix here. However,
- [ ] More clearly mention in docs that all args or default constructor is required.

**Comment by showwiki** [comment]
so ,is this bug fixed?   My objectbox version is 2.9.1. i reproduce it in andoird 7. android 8 , but it works fine in andorid 9 android 10.

**Comment by greenrobot-team** [comment]
@showwiki See https://docs.objectbox.io/getting-started#define-entity-classes TL;DR: for Kotlin data classes add default values for all parameters to ensure a no-param constructor exists.

**Comment by LockdownX7** [comment]
> when i use kotlin data class , i don't know how to define the constructor .

You can just assign a value to each variable's declaration (e.g: `var someString: String = ""`), but if you're trying to set an all-args constructor (which I'd recommend for catching missing default values at compile time), this should work:
```
@Entity
class ExampleEntity(
    @Id var id: Long,
    var someString: String?,
    var anInteger: Int?,
) {
    constructor() : this(0, null, null)
}
```

**Comment by greenrobot-team** [comment]
With `3.0.0` the Gradle plugin will now warn when an `@Entity` class is missing a no-arg (easy to add) or all properties (best for performance) constructor.

Example for an all properties constructor:
```java
@Entity
public class Order {

    @Id
    private long id;
    private ToOne<Customer> customer;
    private ToMany<Order> relatedOrders;

    // All properties constructor for ObjectBox:
    // - make sure type matches exactly,
    // - for ToOne add its virtual ID property instead,
    // - for ToMany add no parameter.
    public Order(long id, long customerId) {
        this.id = id;
        this.customer.setTargetId(customerId);
    }

    // TODO getters and setters for properties
}
```
