### ISSUE TITLE
About new configuration options to open the database with read-only mode

### ISSUE THREAD

**Issue by 1341290135** [objectbox/objectbox-java#908]
MyObjectBox.builder().readOnly() more quickly, so I want use readOnly for query, build another normally for put or remove.

like this:

boxStoreRead = MyObjectBox.builder().readOnly().maxSizeInKByte(lngMaxBoxSize).name("me").androidContext(this).build();
boxStoreWrite = MyObjectBox.builder().maxSizeInKByte(lngMaxBoxSize).name("me").androidContext(this).build();

but find an TimeoutException:
```
------------------------------------------------------------------------------------------------------------------------------
2020-08-31 08:45:03.118 4564-4574/com.ccauo0.administrator.AbcUIDraw E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: com.ccauo0.administrator.AbcUIDraw, PID: 4564
    java.util.concurrent.TimeoutException: io.objectbox.BoxStore.finalize() timed out after 10 seconds
        at io.objectbox.BoxStore.close(BoxStore.java:505)
        at io.objectbox.BoxStore.finalize(BoxStore.java:366)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
        at java.lang.Thread.run(Thread.java:761)
---------------------------------------------------------------------------------------------------------------------------------
```

**Comment by greenrobot-team** [comment]
You still can't have multiple `BoxStore` instances that access the same database in the same process.

`readOnly()` was introduced to e.g. recover data after a failure to open the database or to [use the database from a separate process](https://github.com/objectbox/objectbox-examples/tree/main/android-app-multiprocess).

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Feel free to re-open with more details or submit a new issue.
