### ISSUE TITLE
With ToMany relations: Source entity has no ID (should have been put before)

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#954]
**Describe the bug**
I just implemented a ToMany relation in two models.  After I populate the models and did Box.put, and the app gets an exception with the following errors:

```
E/WordsImporter: Source entity has no ID (should have been put before)
    java.lang.IllegalStateException: Source entity has no ID (should have been put before)
        at io.objectbox.relation.ToMany.internalApplyToDb(ToMany.java:843)
        at io.objectbox.Cursor.checkApplyToManyToDb(Cursor.java:328)
```
I checked the data of the models, and the id is not 0.  

My models are something like the following:
```
@Entity
@Data
@EqualsAndHashCode(callSuper = true)
public class Air extends Element {
    public ToMany<Pair> pairs;
    public Air() { super();}
}

@Entity
@Data
@EqualsAndHashCode(callSuper = true)
public class Pair extends Element {
    public Pair() {super();}
}

@BaseEntity
@Data
public class Element {
    @Id
    public long id;
    @Index
    public String stringId;
    public Element() {;}
}
```
I first put some pairs into the db (so that they have valid ids), then I got the pairs and added them to related airs and I tried to put these airs into db, and that's where the error occurred.  The app doesn't crash, but my import process gets aborted.  I tried it on two phones: an Android 9 and an Android 6.  No difference.

Is there anything I am doing wrong here?

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): [e.g. 2.9.0]
 - Reproducibility: [always]
 - Device: [Nokia 6]
 - OS: [Android 9]

**Comment by LeoK987** [comment]
Went through some debugging.  It looks that when an instance of Air is created, the constructor of Air calls somehow the constructor of ToMany, where the member variable "entity" is assigned to the newly created but not fully initialized Air instance, so entity.id is 0 then.  And it stays that way and never gets updated, so when I add pairs later, the exception is thrown.  Strange it only happens to me is many people are using this.  There must be some thing special in my case.

**Comment by LeoK987** [comment]
Tested with ObjectBox 2.8.1, no difference.

**Comment by LeoK987** [comment]
Sorry, never mind, my bad.  It's working.
